#!/usr/bin/env python3
"""Build the canonical release component/hash manifest.
Run this only after code/config generation and immediately before dist build.

The manifest is intentionally reproducible. Its timestamp comes from the
canonical release descriptor rather than wall-clock build time so rebuilding an
unchanged release produces byte-identical deploy metadata.
"""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
COMPONENTS={
 'index':'index.html',
 'deployment_headers':'_headers',
 'release_descriptor':'config/release.json',
 'runtime_contract':'config/contracts/runtime-contracts.json',
 'runtime_contract_js':'app/generated/runtime-contracts.js',
 'model_config':'config/model-config.json',
 'model_config_js':'app/generated/model-config.js',
 'core_services':'app/core/core-services.js',
 'numeric_contract':'app/core/numeric.js',
 'season_context':'app/core/season-context.js',
 'projection_service':'app/core/projection-service.js',
 'draft_state_service':'app/core/draft-state-service.js',
 'surface_router':'app/core/surface-router.js',
 'special_teams_series':'app/core/special-teams-series.js',
 'draft_value_service':'app/core/draft-value-service.js',
 'data_client':'app/core/data-client.js',
 'cross_position_calibration':'app/core/value-calibration-guard.js',
 'research_report_service':'app/core/research-report-service.js',
 'research_report_ui':'app/research-report-ui.js',
 'research_value_finder_bridge':'app/core/research-value-finder-bridge.js',
 'current_snapshot_store':'app/current-snapshot-store.js',
 'decision_service':'app/core/decision-service.js',
 'semantic_ux':'app/core/semantic-ux.js',
 'semantic_ux_contract':'config/semantic-ux-contract.json',
 'research_lab_ux':'app/core/research-lab-ux.js',
 'research_lab_ux_contract':'config/research-lab-ux-contract.json',
 'repository_lifecycle_contract':'config/repository-lifecycle-contract.json',
 'documentation_cleanup_contract':'config/tranche5d-documentation-cleanup-preflight.json',
 'runtime':'app/runtime-foundation.js',
 'current_player_features':'app/current-player-features.js',
 'decision_model':'app/decision-model-v9.js',
 'decision_engines':'app/decision-engines.js',
 'monte_carlo_worker':'app/draft-monte-carlo-worker.js',
 'value_finder':'app/value-finder.js',
 'portfolio_home':'app/portfolio-home.js',
 'portfolio_config':'app/portfolio-config.js',
 'dst_intelligence':'app/dst-intelligence.js',
 'kicker_intelligence':'app/kicker-intelligence.js',
 'league_context':'app/league-context.js',
 'decision_ui':'app/decision-ui.js',
 'decision_ui_css':'app/decision-ui.css',
 'league_profile':'research/league_profile.py',
 'dst_contract':'research/dst_contract.py',
 'dst_research':'research/fie_dst.py',
 'dst_integrity':'research/integrity_dst_test.py',
 'kicker_contract':'research/kicker_contract.py',
 'kicker_research':'research/fie_kicker.py',
 'kicker_integrity':'research/integrity_kicker_test.py',
 'scoring_relevance':'research/scoring_relevance.py',
 'current_snapshot_builder':'research/build_current_snapshot.py',
 'current_snapshot_storage':'research/current_snapshot_storage.py',
 'current_snapshot_deduper':'research/deduplicate_current_snapshots.py',
 'current_snapshot_storage_integrity':'research/integrity_current_storage_test.py',
 'workflow_decision_context':'research/workflow_decision_context.py',
 'workflow_decision_context_integrity':'research/integrity_workflow_decision_context_test.py',
 'workflow_usability_config':'config/workflow-usability-monitor.json',
 'workflow_usability':'research/workflow_usability.py',
 'workflow_usability_integrity':'research/integrity_workflow_usability_test.py',
 'workflow_usability_workflow':'.github/workflows/report-fie-workflow-usability.yml',
 'workflow_usability_documentation':'docs/audits/WORKFLOW_USABILITY_MONITORING.md',
 'weekly_actions_producer':'research/window1c_weekly_actions.py',
 'window1b_pr2_ownership_integrity':'research/integrity_window1b_pr2_ownership_test.py',
 'optimal_waiver_producer':'research/window1d_optimal_waiver.py',
 'waiver_v2_contract':'research/waiver_v2_contract.py',
 'waiver_v2_contract_integrity':'research/integrity_waiver_v2_contract_test.py',
 'waiver_v2_outcomes':'research/waiver_v2_outcomes.py',
 'waiver_v2_outcomes_integrity':'research/integrity_waiver_v2_outcomes_test.py',
 'waiver_v2_outcome_builder':'research/build_waiver_v2_outcome_ledger.py',
 'waiver_v2_outcome_builder_integrity':'research/integrity_waiver_v2_outcome_build_test.py',
 'waiver_v2_source_adapter':'research/waiver_v2_source_adapter.py',
 'waiver_v2_source_adapter_integrity':'research/integrity_waiver_v2_source_adapter_test.py',
 'waiver_evidence_capture':'research/capture_fie_waivers.py',
 'm10_sunday_checkpoint_design':'config/m10-sunday-paired-checkpoint-design.json',
 'm10_sunday_checkpoint_design_doc':'docs/audits/M10_SUNDAY_PAIRED_CHECKPOINT_DESIGN.md',
 'm10_sunday_checkpoint_design_integrity':'research/integrity_m10_sunday_checkpoint_design.py',
 'm10_sunday_checkpoint_capture':'research/capture_fie_sunday_paired_checkpoint.py',
 'm10_sunday_checkpoint_integrity':'research/integrity_m10_sunday_paired_checkpoint_test.py',
 'm10_legal_roster_assignment_integrity':'research/integrity_m10_legal_roster_assignment_test.py',
 'm10_sunday_checkpoint_write_validator':'research/validate_sunday_paired_checkpoint_write_plan.py',
 'm10_sunday_checkpoint_workflow':'.github/workflows/capture-fie-sunday-paired-checkpoint.yml',
 'workflow_season_calendar':'research/workflow_season_calendar.py',
 'workflow_calendar_control':'research/workflow_calendar_control.py',
 'workflow_calendar_config':'config/workflow-season-calendar.json',
 'workflow_calendar_integrity':'research/integrity_workflow_season_calendar_test.py',
 'workflow_calendar_controller':'.github/workflows/control-fie-workflow-calendar.yml',
 'calendar_wrapper_build_fie_current':'.github/workflows/build-fie-current.yml',
 'calendar_wrapper_build_fie_window1c_weekly_actions':'.github/workflows/build-fie-window1c-weekly-actions.yml',
 'calendar_wrapper_build_fie_window1d_optimal_waiver':'.github/workflows/build-fie-window1d-optimal-waiver.yml',
 'calendar_wrapper_build_fie_window2a_trench_evidence':'.github/workflows/build-fie-window2a-trench-evidence.yml',
 'calendar_wrapper_capture_fie_availability':'.github/workflows/capture-fie-availability.yml',
 'calendar_wrapper_capture_fie_m10_prospective':'.github/workflows/capture-fie-m10-prospective.yml',
 'calendar_wrapper_capture_fie_market':'.github/workflows/capture-fie-market.yml',
 'calendar_wrapper_capture_fie_season_market':'.github/workflows/capture-fie-season-market.yml',
 'calendar_wrapper_capture_fie_waiver_evidence':'.github/workflows/capture-fie-waiver-evidence.yml',
 'calendar_wrapper_capture_fie_weather_evidence':'.github/workflows/capture-fie-weather-evidence.yml',
 'workflow_calendar_reusable':'.github/workflows/_fie-calendar-policy.yml',
 'pr2_lineup_capture':'research/capture_in_season_pr2_lineup_evidence.py',
 'pr2_lineup_capture_integrity':'research/integrity_in_season_pr2_lineup_capture_test.py',
 'pr2_lineup_capture_workflow_integrity':'research/integrity_in_season_pr2_lineup_workflow_test.py',
 'pr2_lineup_outcome_schedule':'research/resolve_in_season_pr2_lineup_outcome_target.py',
 'pr2_lineup_outcome_schedule_integrity':'research/integrity_in_season_pr2_lineup_outcome_schedule_test.py',
 'pr2_lineup_outcome_workflow_integrity':'research/integrity_in_season_pr2_lineup_outcome_workflow_test.py',
 'pr2_lineup_release_gate':'research/integrity_in_season_pr2_release_gate.py',
 'pr2_lineup_capture_workflow':'.github/workflows/capture-fie-pr2-weekly-lineups.yml',
 'pr2_lineup_outcome_workflow':'.github/workflows/evaluate-fie-pr2-weekly-lineups.yml',
 'availability_evidence_capture':'research/capture_fie_availability.py',
 'availability_capture_integrity':'research/integrity_availability_capture_test.py',
 'availability_backbone_integrity':'research/integrity_window1a_evidence_backbone.py',
 'availability_v2_preservation_integrity':'research/integrity_window2c_availability_v2_test.py',
 'point_in_time_inventory':'research/build_fie_point_in_time_evidence_report.py',
 'waiver_capture_reconciliation':'research/waiver_capture_reconciliation.py',
 'waiver_capture_reconciliation_integrity':'research/integrity_waiver_capture_reconciliation_test.py',
 'evidence_capture_validator':'research/validate_window1a_evidence.py',
 'league_app_snapshot_builder':'research/build_league_app_snapshots.py',
 'league_fast_switch_integrity':'research/integrity_league_fast_switch_test.py',
 'league_fast_switch_runtime_integrity':'research/integrity_league_fast_switch_runtime_test.js',
 'completion_15point_integrity':'research/integrity_15point_completion_test.py',
 'cross_position_calibration_integrity':'research/integrity_cross_position_calibration_test.js',
 'league_app_dist_sync':'tools/sync_league_app_snapshots.py',
 'research_pipeline_contract':'research/fie_research_pipeline_contract.py',
 'research_pipeline_runner':'research/run_fie_league_research_pipeline.py',
 'research_position_resolver':'research/resolve_fie_position_models.py',
 'research_final_board':'research/build_fie_final_league_board.py',
 'research_league_report':'research/build_fie_league_research_report.py',
 'research_portfolio_report':'research/build_fie_portfolio_research_report.py',
 'research_app_contract_publisher':'research/publish_fie_research_app_contract.py',
 'research_pipeline_integrity':'research/integrity_fie_research_pipeline_test.py',
 'research_app_contract_integrity':'research/integrity_fie_app_research_contract_test.js',
 'decision_validation':'research/decision_validation.py',
 'decision_validation_contract':'research/decision_validation_contract.json',
 'dist_builder':'tools/build_dist.py',
 'release_builder':'tools/release_build.py',
 'manifest_builder':'research/build_app_manifest.py',
 'build_determinism_integrity':'research/integrity_v932_build_determinism_test.py',
 'release_gate':'research/release_gate.py',
 'repository_lifecycle_integrity':'research/integrity_tranche5c_documentation_lifecycle.py',
 'documentation_cleanup_integrity':'research/integrity_tranche5d_documentation_cleanup.py',
 'regression_closure_preflight_contract':'config/tranche5e-regression-closure-preflight.json',
 'regression_closure_target_contract':'config/tranche5e-regression-closure-target.json',
 'regression_closure_integrity':'research/integrity_tranche5e_regression_closure.py',
}
def sha(path):
 h=hashlib.sha256()
 with path.open('rb') as f:
  for chunk in iter(lambda:f.read(1<<20),b''):h.update(chunk)
 return h.hexdigest()
def release_timestamp(release):
 ts=str(release.get('built_at') or '').strip()
 if not ts:raise ValueError('config/release.json built_at is required for deterministic build manifests')
 return ts
def build():
 release=json.loads((ROOT/'config/release.json').read_text());files={}
 for name,rel in COMPONENTS.items():
  p=ROOT/rel
  if not p.exists():raise FileNotFoundError(rel)
  files[name]={'path':rel,'sha256':sha(p),'bytes':p.stat().st_size}
 return {'schema_version':2,'app_version':release['release'],'runtime_version':release['runtime'],'draft_model_version':release['decision_model'],'value_finder_version':release['value_finder'],'research_generation':release['research_schema'],'model_promotion':json.loads((ROOT/'config/model-config.json').read_text()).get('production',{}),'runtime_research_scope':'league_namespaced_only','generated_at':release_timestamp(release),'files':files}
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--output',default='config/build-manifest.json');a=ap.parse_args();out=ROOT/a.output;out.parent.mkdir(parents=True,exist_ok=True);out.write_text(json.dumps(build(),indent=2)+'\n', encoding='utf-8', newline='\n');print(out.relative_to(ROOT))
if __name__=='__main__':main()
