/* Fictional provider endpoints in the real application; never live validation. */
'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const {chromium}=require(process.env.FIE_UI_PLAYWRIGHT||'playwright');
const root=path.resolve(process.argv[2]||'dist'),out=path.resolve(process.env.FIE_UI_QA_OUTPUT||'editorial-live-draft-qa');fs.mkdirSync(out,{recursive:true});
(async()=>{
 const server=await new Promise(resolve=>{const s=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost'),f=path.resolve(root,'.'+(u.pathname==='/'?'/index.html':u.pathname));if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(f,(err,b)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':f.endsWith('.json')?'application/json':'text/html');res.end(b);});}).listen(0,'127.0.0.1',()=>resolve(s));});
 const browser=await chromium.launch({headless:true}),report={mode:'Fictional provider reads and loaded records. Not live league validation.',samples:[]};
 try{for(const width of [1440,390,320,720]){
  const context=await browser.newContext({viewport:{width,height:1000}});await context.route('https://**/*',r=>r.abort());const page=await context.newPage(),errors=[],reads=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`,{waitUntil:'load'});await page.waitForFunction(()=>window.FIELiveDraftWorkspace&&window.FIEPortfolioConfig.loaded&&!window.FIEPortfolio.refreshing);
  const provider=await page.evaluate(()=>{
   state.league={league_id:'fixture',name:'Fictional live draft',season:'2026',status:'drafting',total_rosters:2,roster_positions:['QB','RB','WR','SUPER_FLEX','IDP_FLEX','BN'],scoring_settings:{pass_yd:.04,rec:1,tkl:1},settings:{type:0}};
   state.rosters=[{roster_id:1,owner_id:'one',players:[],starters:[]},{roster_id:2,owner_id:'two',players:[],starters:[]}];state.users=[{user_id:'one',display_name:'Fictional A'},{user_id:'two',display_name:'Fictional B'}];state.selectedRoster=1;state.matched=true;state.leagueRules={...state.leagueRules,format:'REDRAFT',allowedExperience:['R','Y2']};
   PLAYERS=Array.from({length:46},(_,i)=>({sleeperId:String(1000+i),name:'Live '+String(i).padStart(2,'0'),position:['QB','RB','WR','LB'][i%4],side:i%4===3?'IDP':'OFF',team:'BUF',yearsExp:1,leagueEligible:true,availability:'FA',ownerRosterId:null,engineSeasonProjection:i===0?0:200-i,weeklyProjection:10-i/10,projectedVOR:i===0?0:50-i,currentOpportunity:60,targetScore:65,leagueFit:70,weeklyFloor:5,weeklyCeiling:20,marketADP:i===0?null:20+i*5,seasonScore:60,role:'Starter',depthChartOrder:1,injuryStatus:'Healthy'}));
   PLAYERS.push({...PLAYERS[1],sleeperId:'999',name:'Ineligible veteran',leagueEligible:false,yearsExp:20});state.projectionStatus={...state.projectionStatus,season:true,seasonCount:46};
   const draft={draft_id:'live',league_id:'fixture',season:'2026',status:'drafting',type:'snake',settings:{teams:2,rounds:25,reversal_round:3},slot_to_roster_id:{1:1,2:2},draft_order:{one:1,two:2}},picks=[{pick_no:1,player_id:'1001',roster_id:1,draft_slot:1,round:1}];
   state.draftIntel={...state.draftIntel,loaded:true,loading:false,error:null,selectedDraftId:'live',draft,drafts:[draft],picks,tradedPicks:[]};state.draftContext={...state.draftContext,loaded:true};populateFilters();populateRosterPicker();populateDraftControls();document.getElementById('searchFilter').value='';document.getElementById('posFilter').value='ALL';FIEDraftBaseValueService.invalidate();FIEPortfolio.leave();activateTab('draftassistant');return {draft,picks};
  });
  await context.route('https://api.sleeper.app/v1/**',async r=>{const url=r.request().url();reads.push({url,cache:r.request().headers()['cache-control']});const body=url.endsWith('/drafts')?[provider.draft]:url.endsWith('/picks')?provider.picks:url.endsWith('/traded_picks')?[]:provider.draft;await r.fulfill({json:body});});
  const host=page.locator('#draftAssistantSummary'),shot=async n=>page.screenshot({path:path.join(out,`${n}-${width}.png`),fullPage:true}),overflow=async()=>assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Page horizontal overflow');
  assert((await host.innerText()).includes('age unknown'));assert(!/TAKE NOW/.test(await host.innerText()));
  await page.evaluate(()=>loadDraftIntel());await page.getByRole('heading',{name:'Now / next pick candidates',exact:true}).waitFor();assert(await page.evaluate(()=>FIELiveDraftWorkspace.health().ready));assert(reads.some(x=>x.url.endsWith('/traded_picks')));assert.equal(await host.locator('.fie-expanded:visible').count(),0);
  assert.equal(await page.locator('#draftAssistantPanel h2').first().innerText(),'Live Draft Assistant');assert.equal(await host.locator('.fie-live-context dd').nth(2).innerText(),'4');assert(!/TAKE NOW/.test(await host.innerText()));assert((await host.innerText()).includes('Your acquired roster'));await overflow();await shot('assistant-basic');
  const candidate=host.locator('.fie-disclosure').first();assert.equal(await candidate.locator('tbody tr:not(.fie-expanded)').count(),3);await candidate.getByRole('button',{name:/Expand /}).first().click();assert((await candidate.innerText()).includes('existing utility/component units'));await shot('assistant-expanded');
  const advanced=candidate.getByRole('button',{name:/Advanced evidence/}).first();await advanced.click();await page.locator('dialog[open]').waitFor();assert((await page.locator('dialog[open]').innerText()).includes('Captured decision record'));await shot('candidate-advanced');await page.keyboard.press('Escape');assert(await advanced.evaluate(e=>e===document.activeElement));
  const player=candidate.getByRole('button',{name:'Player details',exact:true}).first();await player.click();await page.locator('dialog[open]').waitFor();await page.keyboard.press('Escape');assert(await player.evaluate(e=>e===document.activeElement));
  await page.locator('#draftRosterPicker').selectOption('2');assert.equal(await host.locator('.fie-live-context dd').nth(1).innerText(),'2');await page.locator('#draftRosterPicker').selectOption('1');
  await host.locator('summary').filter({hasText:'Complete roster'}).click();await page.getByRole('heading',{name:'Complete acquired roster',exact:true}).waitFor();await host.getByRole('button',{name:'Advanced · Legal roster assignment',exact:true}).click();await page.locator('dialog[open]').waitFor();assert((await page.locator('dialog[open]').innerText()).includes('Existing optimizer'));await page.keyboard.press('Escape');
  await host.locator('summary').filter({hasText:'Draft log'}).click();await page.getByRole('heading',{name:'Observed draft log',exact:true}).waitFor();await shot('roster-and-log');
  await page.evaluate(()=>activateTab('draft'));await page.getByRole('heading',{name:'Available draft board',exact:true}).waitFor();const board=page.locator('#fieLiveDraft'),boardTable=board.locator('.fie-disclosure').first();assert.equal(await boardTable.locator('tbody tr:not(.fie-expanded)').count(),40);assert(!await boardTable.getByText('Live 01 · RB · BUF',{exact:true}).count());assert(!/Ineligible veteran/.test(await boardTable.innerText()));await board.getByRole('button',{name:'Show 5 more',exact:true}).click();assert.equal(await boardTable.locator('tbody tr:not(.fie-expanded)').count(),45);
  const parity=await page.evaluate(()=>{const owner=FIEDraftBaseValueService.rows(),ranks=FIEDecisionService.draftRows(1).filter(x=>String(x.p.sleeperId)!=='1001'&&!x.p.drafted&&isLeagueEligible(x.p)).sort((a,b)=>(b.score??b.decisionScore)-(a.score??a.decisionScore));return [...document.querySelectorAll('#fieLiveDraft .fie-disclosure:first-of-type tbody tr:not(.fie-expanded)')].map(tr=>{const text=tr.children[1].textContent,x=owner.find(x=>text.startsWith(x.p.name+' · '));return {rank:tr.children[0].textContent,value:tr.children[2].textContent,priority:tr.children[3].textContent,expectedRank:String(x.overallRank),expectedValue:Number(x.baseValue).toFixed(1),expectedPriority:String(ranks.findIndex(r=>String(r.p.sleeperId)===String(x.p.sleeperId))+1)};});});for(const x of parity){assert.equal(x.rank,x.expectedRank);assert.equal(x.value,x.expectedValue);assert.equal(x.priority,x.expectedPriority);}await overflow();await shot('board');
  await page.locator('#searchFilter').fill('Live 00');await page.waitForFunction(()=>document.querySelectorAll('#fieLiveDraft .fie-disclosure:first-of-type tbody tr:not(.fie-expanded)').length===1);await boardTable.getByRole('button',{name:/Expand /}).click();assert((await boardTable.innerText()).includes('0.0 points'));await page.locator('#searchFilter').fill('');
  await page.evaluate(()=>activateTab('valuefinder'));await page.getByRole('heading',{name:'Available market values',exact:true}).waitFor();const values=page.locator('#valueFinderSummary');assert(!/Live 00|Live 01 ·|TAKE NOW/.test(await values.innerText()));await overflow();await shot('values');
  await values.getByRole('button',{name:'Advanced · Existing pick optimizer and scenarios',exact:true}).click();await page.locator('.vf-table').waitFor();await page.getByRole('button',{name:'Back to Basic live values',exact:true}).click();await page.getByRole('heading',{name:'Available market values',exact:true}).waitFor();
  const reader=values.getByRole('button',{name:/Advanced evidence/}).first();await reader.click();await page.locator('dialog[open]').waitFor();await page.evaluate(()=>{const original=Date.now;window.fixtureRestoreClock=()=>Date.now=original;Date.now=()=>original()+31000;});await page.waitForFunction(()=>!document.querySelector('dialog[open]')&&document.querySelector('#valueFinderSummary').textContent.includes('Snapshot expired'));assert(!/\d+\.\d+% · Estimate/.test(await values.innerText()));await shot('expired');await page.evaluate(()=>{fixtureRestoreClock();render();});await page.evaluate(()=>loadDraftIntel());
  await values.getByRole('button',{name:'Advanced · Existing pick optimizer and scenarios',exact:true}).click();await page.locator('.vf-table').waitFor();await page.evaluate(()=>{const original=Date.now;window.fixtureRestoreClock=()=>Date.now=original;Date.now=()=>original()+31000;});await page.waitForFunction(()=>!document.querySelector('.vf-table')&&document.querySelector('#valueFinderSummary').textContent.includes('Snapshot expired'));assert.equal(await page.locator('#fieLiveLegacyReturn:visible').count(),0);await page.evaluate(()=>{fixtureRestoreClock();render();});await page.evaluate(()=>loadDraftIntel());
  await page.evaluate(()=>{state.league={...state.league,league_id:'other'};activateTab('draftassistant');});assert.equal(await host.locator('.fie-disclosure').count(),0);assert((await host.innerText()).includes('does not match'));await page.evaluate(()=>{state.league={...state.league,league_id:'fixture'};render();});await page.evaluate(()=>loadDraftIntel());
  await page.evaluate(()=>{state.draftIntel.picks.push({pick_no:2,player_id:'1002',draft_slot:2,roster_id:2,round:1},{pick_no:3,player_id:'1003',draft_slot:2,roster_id:2,round:2},{pick_no:4,player_id:'1004',draft_slot:1,roster_id:1,round:2});FIELiveDraftWorkspace.completeRefresh(FIELiveDraftWorkspace.beginRefresh(state.league,'live'));render();});assert(await page.evaluate(()=>FIELiveDraftWorkspace.health().ready));assert.equal(await host.locator('.fie-live-context dd').nth(2).innerText(),'6');await page.evaluate(()=>loadDraftIntel());
  for(const [kind,label]of [['paused','Draft paused'],['gap','Conflicting pick ledger'],['trade','ownership unverified'],['foreign','does not match'],['error','Refresh failed']]){
   await page.evaluate(kind=>{if(kind==='paused')state.draftIntel.draft.status='paused';if(kind==='gap')state.draftIntel.picks.push({pick_no:3,player_id:'1002',draft_slot:2});if(kind==='trade')state.draftIntel.tradedPicks=[{season:'2026'}];if(kind==='foreign')state.draftIntel.draft.league_id='other';if(kind==='error')state.draftIntel.error='fixture failure';FIELiveDraftWorkspace.completeRefresh(FIELiveDraftWorkspace.beginRefresh(state.league,state.draftIntel.selectedDraftId));activateTab('draftassistant');},kind);
   assert((await host.innerText()).includes(label));assert(!/TAKE NOW/.test(await host.innerText()));if(['foreign','error'].includes(kind))assert.equal(await host.locator('.fie-disclosure').count(),0);await page.evaluate(()=>loadDraftIntel());
  }
  await page.evaluate(()=>{state.selectedRoster=2;state.draftIntel.picks.push({pick_no:2,player_id:'unresolved',draft_slot:2,roster_id:2,round:1});FIELiveDraftWorkspace.completeRefresh(FIELiveDraftWorkspace.beginRefresh(state.league,'live'));render();});assert((await host.innerText()).includes('Unresolved unresolved'));assert(await page.evaluate(()=>FIELiveDraftWorkspace.health().ready));assert.equal(await host.locator('.fie-live-context dd').nth(0).innerText(),'3');await page.evaluate(()=>loadDraftIntel());
  await page.evaluate(()=>activateTab('all'));await page.getByRole('heading',{name:'Player explorer',exact:true}).waitFor();assert(!await board.isVisible());assert(!await page.evaluate(()=>document.body.classList.contains('fie-live-draft-active')));
  for(const format of ['DYNASTY','REDRAFT_BESTBALL','DYNASTY_BESTBALL','CHOPPED','CHOPPED_BESTBALL']){await page.evaluate(f=>{state.leagueRules.format=f;FIEDraftBaseValueService.invalidate();activateTab('draft');},format);await page.getByRole('heading',{name:'Available draft board',exact:true}).waitFor();await overflow();}
  await page.evaluate(()=>{state.draftIntel.draft.status='pre_draft';state.draftIntel.picks=[];activateTab('draftassistant');});await page.getByRole('heading',{name:'Top Picks',exact:true}).waitFor();await page.evaluate(()=>{state.draftIntel.draft.status='complete';activateTab('draftassistant');});assert.equal(await page.locator('#draftAssistantPanel h2').innerText(),'Draft Assistant');assert.equal(await page.getByRole('heading',{name:'Now / next pick candidates',exact:true}).count(),0);
  assert.deepStrictEqual(errors,[],'Uncaught browser errors');report.samples.push({width,status:'PASS',providerReads:reads.length,errors});await context.close();
 }report.status='PASS';fs.writeFileSync(path.join(out,'comparison.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));}finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
