/* Populated offline real-app Phase 4 review. Fixtures are fictional, not live league evidence. */
'use strict';const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');const {chromium}=require(process.env.FIE_UI_PLAYWRIGHT||'playwright');
const root=path.resolve(process.argv[2]||'dist'),out=path.resolve(process.env.FIE_UI_QA_OUTPUT||'editorial-overview-qa');fs.mkdirSync(out,{recursive:true});
const fixtures=[{roster_id:1,matchup_id:1,points:0,custom_points:0,starters:['1001','1002'],starters_points:[-2,0],players:['1001','1002'],players_points:{1001:-2,1002:0}},{roster_id:2,matchup_id:1,points:12,starters:['1003'],starters_points:[12],players:['1003'],players_points:{1003:12}}];
(async()=>{const server=await new Promise(resolve=>{const s=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost'),f=path.resolve(root,'.'+(u.pathname==='/'?'/index.html':u.pathname));if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(f,(err,b)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':f.endsWith('.json')?'application/json':'text/html');res.end(b);});}).listen(0,'127.0.0.1',()=>resolve(s));});const browser=await chromium.launch({headless:true}),report={mode:'Fictional provider + portfolio fixtures in the real app. Not live league validation.',samples:[]};try{for(const width of [1440,390]){
 const context=await browser.newContext({viewport:{width,height:width===390?844:1000}}),page=await context.newPage();let fail=false,delay=0;
 await context.route('https://**/*',async r=>{const u=r.request().url();if(u.includes('/state/nfl'))return r.fulfill({json:{season:'2026',display_week:5,season_type:'regular'}});if(u.includes('/matchups/')){if(delay)await new Promise(x=>setTimeout(x,delay));return fail?r.fulfill({status:503,body:'Unavailable'}):r.fulfill({json:fixtures});}return r.abort();});
 await context.route('**/data/ui/waivers/index.json',r=>r.fulfill({json:{leagues:{'999999999999999999':'data/ui/waivers/leagues/999999999999999999.json'},documents:[],portfolio_reports:[{season:2026,week:4,league_count:1,league_ids:['999999999999999999'],league_statuses:{'999999999999999999':'BLOCKED_PROFILE_DRIFT'},status_counts:{BLOCKED_PROFILE_DRIFT:1},captured_at:'2026-09-30T12:00:00Z',source:{path:'fictional/report.json',sha256:'qa-only'}}]}}));
 await context.route('**/data/ui/waivers/leagues/999999999999999999.json',r=>r.fulfill({json:{league_id:'999999999999999999',reports:[{season:2026,week:4,captured_at:'2026-09-30T12:00:00Z',report:{league_id:'999999999999999999',status:'BLOCKED_PROFILE_DRIFT'}}],history:[]}}));
 await page.goto(`http://127.0.0.1:${server.address().port}`,{waitUntil:'load'});await page.waitForFunction(()=>!!window.FIEOverviewWorkspace&&!!window.FIEPortfolioConfig.loaded&&!window.FIEPortfolio.refreshing);
 await page.evaluate(()=>{const ids=['999999999999999999','888888888888888888','777777777777777777','666666666666666666'];const names=['Fictional priority league','Retained chopped evidence','Future draft league','Unknown coverage league'];FIEPortfolioConfig.config={sleeper_username:'C0nstant1n',leagues:ids.map((league_id,i)=>({league_id,alias:names[i],format:i===1?'CHOPPED':'REDRAFT',priority:i===0?'VERY_HIGH':'LOW',lifecycle:i===1?'ELIMINATED':undefined}))};FIEPortfolioConfig.status={leagues:Object.fromEntries(ids.map((id,i)=>[id,{season:'2026',historical_research:i<2,status:i<2?'READY':'REFRESH_ONLY'}]))};const es=ids.map((id,i)=>({id,name:names[i],season:'2026',formatOverride:i===1?'CHOPPED':'REDRAFT',priority:i===0?'VERY_HIGH':'LOW'}));localStorage.setItem('fieSavedLeaguesV71',JSON.stringify(es));localStorage.setItem('fiePortfolioMetaV1',JSON.stringify({[ids[0]]:{league:{season:'2026',status:'in_season'},checkedAt:'2026-09-01T00:00:00Z'},[ids[1]]:{league:{status:'in_season'},checkedAt:'2026-09-01T00:00:00Z'},[ids[2]]:{league:{status:'pre_draft'},drafts:[{status:'pre_draft',start_time:Date.now()+86400000}]}}));localStorage.setItem('fiePortfolioSnapshotsV1',JSON.stringify({[ids[0]]:{leagueId:ids[0],season:2026,rosterId:1,generatedAt:'2026-09-01T00:00:00Z',items:[{route:'waivers',title:'CLAIM NOW',note:'FAAB rec 90'}]}}));FIEPortfolio.render();});
 await page.getByRole('heading',{name:'League overview',exact:true}).waitFor();assert(await page.getByRole('rowheader',{name:'Retained chopped evidence',exact:true}).isVisible());assert(await page.getByRole('cell',{name:/Eliminated · evidence retained/}).isVisible());assert(!(await page.locator('#portfolioSummary').innerText()).includes('CLAIM NOW'));assert.strictEqual(await page.locator('#portfolioSummary .fie-expanded:visible').count(),0);
 await page.evaluate(()=>scrollTo(0,0));const basic=await page.evaluate(()=>({firstRowTop:document.querySelector('#portfolioSummary table tbody tr')?.getBoundingClientRect().top,documentWidth:document.documentElement.scrollWidth,viewport:innerWidth}));assert(basic.documentWidth<=width+1);assert(basic.firstRowTop+35<(width===390?844:1000),'First league row in first viewport');await page.screenshot({path:path.join(out,`portfolio-${width}.png`),fullPage:true});
 await page.getByRole('button',{name:'Expand Fictional priority league',exact:true}).click();assert(await page.getByText('2026-09-01T00:00:00Z',{exact:true}).first().isVisible());await page.screenshot({path:path.join(out,`portfolio-expanded-${width}.png`),fullPage:true});
 const adv=page.getByRole('button',{name:'Advanced evidence for Fictional priority league',exact:true});await adv.click();assert(await page.getByText(/Cached device analysis/).isVisible());await page.screenshot({path:path.join(out,`portfolio-advanced-${width}.png`),fullPage:true});await page.keyboard.press('Escape');assert(await adv.evaluate(e=>document.activeElement===e));
 await page.locator('#portfolioSummary summary').filter({hasText:'Owned-player exposure'}).click();await page.getByText(/0 known managed-roster snapshots/).waitFor();await page.screenshot({path:path.join(out,`exposure-unknown-${width}.png`),fullPage:true});
 await page.evaluate(()=>{state.league={league_id:'999999999999999999',name:'Fictional priority league',season:'2026',total_rosters:2,roster_positions:['QB','RB','BN'],scoring_settings:{rec:1},settings:{type:0,best_ball:0,waiver_budget:100},status:'in_season'};state.rosters=[{roster_id:1,owner_id:'one',players:['1001','1002'],settings:{waiver_budget_used:0}},{roster_id:2,owner_id:'two',players:['1003'],settings:{waiver_budget_used:20}}];state.users=[{user_id:'one',username:'C0nstant1n',display_name:'Your fictional team'},{user_id:'two',username:'Other',display_name:'Fictional opponent'}];PLAYERS=[{sleeperId:'1001',name:'Alex River',position:'QB',team:'BUF',availability:'OWNED',ownerRosterId:1,leagueEligible:true,yearsExp:1,side:'OFF',weeklyProjection:10},{sleeperId:'1002',name:'Casey Quinn',position:'RB',team:'BUF',availability:'OWNED',ownerRosterId:1,leagueEligible:true,yearsExp:1,side:'OFF',weeklyProjection:12},{sleeperId:'1003',name:'Opponent QB',position:'QB',team:'BUF',availability:'OWNED',ownerRosterId:2,leagueEligible:true,yearsExp:1,side:'OFF',weeklyProjection:14}];state.selectedRoster=1;state.matched=true;state.weekly={...state.weekly,season:2026,week:5,loaded:true,schedule:[]};populateRosterPicker();document.getElementById('weekSelect').value='5';document.getElementById('kLeague').textContent=state.league.name;document.getElementById('status').textContent='Fictional test data · not live league evidence';FIEPortfolio.leave();activateTab('home');});
 await page.getByText('0.00 – 12.00 pts · Loss',{exact:true}).waitFor();assert((await page.locator('#homeSummary').innerText()).includes('Week 4'));await page.evaluate(()=>scrollTo(0,0));const home=await page.evaluate(()=>({resultTop:document.querySelector('#homeSummary .fie-overview-result')?.getBoundingClientRect().top,documentWidth:document.documentElement.scrollWidth,viewport:innerWidth}));assert(home.documentWidth<=width+1);assert(home.resultTop+60<(width===390?844:1000),'Reported result in first viewport');await page.screenshot({path:path.join(out,`home-${width}.png`),fullPage:true});
 await page.locator('#homeSummary summary').filter({hasText:'Result contributors'}).click();await page.getByRole('cell',{name:/-2.00/}).waitFor();assert(await page.getByRole('cell',{name:/0.00/}).first().isVisible());await page.screenshot({path:path.join(out,`home-expanded-${width}.png`),fullPage:true});
 await page.getByRole('combobox',{name:'Home roster',exact:true}).selectOption('2');await page.getByText('12.00 – 0.00 pts · Win',{exact:true}).waitFor();assert.strictEqual(await page.locator('#homeSummary .fie-expanded:visible').count(),0);await page.waitForFunction(()=>location.hash.includes('roster=2'));await page.evaluate(()=>history.back());await page.getByText('0.00 – 12.00 pts · Loss',{exact:true}).waitFor();await page.evaluate(()=>history.forward());await page.getByText('12.00 – 0.00 pts · Win',{exact:true}).waitFor();
 await page.locator('#homeSummary summary').filter({hasText:'League reports'}).click();await page.getByRole('cell',{name:/Research only · league blocked/}).waitFor();await page.getByRole('button',{name:'Open league evidence',exact:true}).click();await page.getByRole('heading',{name:'League evidence',exact:true}).waitFor();assert.equal(await page.locator('#weekSelect').inputValue(),'4');await page.evaluate(()=>activateTab('home'));await page.getByText('12.00 – 0.00 pts · Win',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Open Weekly results',exact:true}).click();await page.getByRole('heading',{name:'Submitted lineup',exact:true}).waitFor();assert.equal(await page.locator('#weekSelect').inputValue(),'4');
 await page.evaluate(()=>{FIEPortfolio.show();});await page.getByRole('heading',{name:'League overview',exact:true}).waitFor();await page.locator('#portfolioSummary summary').filter({hasText:'Owned-player exposure'}).click();await page.getByText(/1 known managed-roster snapshots \/ 3 non-retained leagues/).waitFor();await page.getByRole('rowheader',{name:'Alex River',exact:true}).waitFor();assert(!(await page.getByRole('rowheader',{name:'Opponent QB',exact:true}).count()));await page.screenshot({path:path.join(out,`exposure-known-${width}.png`),fullPage:true});
 await page.getByRole('searchbox',{name:'Find a league',exact:true}).fill('Retained');assert.equal(await page.locator('#portfolioSummary .fie-disclosure').filter({has:page.getByRole('heading',{name:'League overview',exact:true})}).locator('tbody tr:not(.fie-expanded)').count(),1);await page.getByRole('button',{name:'Expand Retained chopped evidence',exact:true}).click();assert(!(await page.locator('#portfolioSummary').innerText()).includes('Set lineup'));
 await page.evaluate(()=>{FIEPortfolio.leave();activateTab('home');});await page.getByText('12.00 – 0.00 pts · Win',{exact:true}).waitFor();fail=true;await page.getByRole('button',{name:'Refresh result',exact:true}).click();await page.getByText(/Unavailable · HTTP 503/).waitFor();await page.screenshot({path:path.join(out,`home-blocked-${width}.png`),fullPage:true});fail=false;
 delay=300;await page.getByRole('button',{name:'Refresh result',exact:true}).click();await page.evaluate(()=>{window.dispatchEvent(new Event('fie:league-changing'));state.league={...state.league,league_id:'888888888888888888',name:'Retained chopped evidence'};state.leagueRules.format='CHOPPED';FIEOverviewWorkspace.home();});await page.getByText(/survival unverified/).first().waitFor();await page.waitForTimeout(400);assert(!(await page.getByText('12.00 – 0.00 pts · Win',{exact:true}).count()));await page.screenshot({path:path.join(out,`home-chopped-${width}.png`),fullPage:true});
 report.samples.push({width,portfolio:basic,home});await context.close();
 }report.status='PASS';fs.writeFileSync(path.join(out,'comparison.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
