/* Phase 7 journeys. Real app + served archive metadata; provider outcomes are explicitly fictional. */
'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const {chromium}=require(process.env.FIE_UI_PLAYWRIGHT||'playwright');
const root=path.resolve(process.argv[2]||'dist'),previous=path.resolve(process.argv[3]||'../fie-editorial-p06/dist'),out=path.resolve(process.env.FIE_UI_QA_OUTPUT||'editorial-journey-qa');fs.mkdirSync(out,{recursive:true});
const lid='999999999999999999',other='888888888888888888';
const matchups=[{roster_id:1,matchup_id:1,points:5.5,starters:['1001','1002'],starters_points:[0,5.5],players:['1001','1002'],players_points:{1001:0,1002:5.5}},{roster_id:2,matchup_id:1,points:4,starters:['1003'],starters_points:[4],players:['1003'],players_points:{1003:4}}];
const waiverIndex={leagues:{[lid]:`data/ui/waivers/leagues/${lid}.json`,[other]:`data/ui/waivers/leagues/${other}.json`},documents:[],portfolio_reports:[]};
const waiver=league_id=>({league_id,reporting_only:true,reports:[{season:2026,week:3,captured_at:'2026-09-20T12:00:00Z',source:{path:'fictional/qa-only.json',sha256:'fixture-only'},report:{league_id,status:'BLOCKED_NO_ELIGIBLE_WAIVER_PROJECTIONS',research_only:true}}],history:[]});
function rgb(s){const m=s.match(/[\d.]+/g)||[];return m.slice(0,3).map(Number);}
function contrast(a,b){const lum=x=>x.map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;}).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0);const x=lum(a),y=lum(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05);}
async function inject(page,format='REDRAFT',id=lid){await page.evaluate(({format,id})=>{
 state.league={league_id:id,name:'Fictional journey league '+id.slice(0,3),season:'2026',status:'in_season',total_rosters:2,roster_positions:['QB','RB','SUPER_FLEX','DEF','K','IDP_FLEX','BN'],scoring_settings:{pass_yd:.04,rec:1},settings:{type:format==='DYNASTY'?2:0,best_ball:format.includes('BESTBALL')?1:0,waiver_budget:100}};
 state.leagueRules={...state.leagueRules,format,allowedExperience:['R','Y2','Y3','Y4','VET']};
 state.rosters=[{roster_id:1,owner_id:'one',players:['1001','1002','1004'],starters:['1001','1002'],settings:{wins:0,losses:1,ties:0,fpts:0,fpts_decimal:0,waiver_budget_used:0}},{roster_id:2,owner_id:'two',players:['1003'],starters:['1003'],settings:{wins:1,losses:0,ties:0,fpts:4,fpts_decimal:0,waiver_budget_used:100}}];
 state.users=[{user_id:'one',username:'C0nstant1n',display_name:'Fictional roster A'},{user_id:'two',username:'Other',display_name:'Fictional roster B'}];
 const base={team:'BUF',leagueEligible:true,yearsExp:1,age:24,currentOpportunity:50,targetScore:50,seasonScore:50,side:'OFF',availability:'OWNED',projectionScoringExact:false};
 PLAYERS=[{...base,sleeperId:'1001',name:'Journey Zero',position:'QB',ownerRosterId:1,owner:'Fictional roster A',engineSeasonProjection:0,weeklyProjection:0,projectedVOR:0},{...base,sleeperId:'1002',name:'Journey Runner',position:'RB',ownerRosterId:1,engineSeasonProjection:100,weeklyProjection:7,projectedVOR:5},{...base,sleeperId:'1003',name:'Journey Opponent',position:'QB',ownerRosterId:2,engineSeasonProjection:90,weeklyProjection:4,projectedVOR:0},{...base,sleeperId:'1004',name:'Journey Defender',position:'LB',side:'IDP',ownerRosterId:1,engineSeasonProjection:70,weeklyProjection:5,projectedVOR:0},{...base,sleeperId:'1005',name:'Journey Free Agent',position:'WR',availability:'FA',ownerRosterId:null,engineSeasonProjection:null,weeklyProjection:null,projectedVOR:null}];
 state.selectedRoster=1;state.matched=true;state.weekly={...state.weekly,season:2026,week:3,loaded:true,schedule:[]};state.projectionStatus={...state.projectionStatus,weekly:true,weeklyContext:{leagueId:id,season:2026,week:5}};state.draftIntel={...state.draftIntel,loaded:true,tradedPicks:[]};state.transactions={loaded:true,loading:false,rows:[],profiles:{},summary:{transactions:0},errors:[]};
 populateFilters();populateRosterPicker();document.getElementById('weekSelect').value='3';document.getElementById('kLeague').textContent=state.league.name;document.getElementById('status').textContent='Fictional provider fixture · not live results';FIEPortfolio.leave();activateTab('startsit');
 },{format,id});}
(async()=>{const server=await new Promise(resolve=>{const s=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost'),isPrevious=u.pathname.startsWith('/previous/'),base=isPrevious?previous:root,rel=isPrevious?u.pathname.slice('/previous'.length):u.pathname,f=path.resolve(base,'.'+(rel==='/'?'/index.html':rel));if(!f.startsWith(base+path.sep)){res.writeHead(403).end();return;}fs.readFile(f,(e,b)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':f.endsWith('.json')?'application/json':'text/html');res.end(b);});}).listen(0,'127.0.0.1',()=>resolve(s));});
 const browser=await chromium.launch({headless:true}),url=`http://127.0.0.1:${server.address().port}`,report={mode:'Offline real-app journeys with explicit fictional provider outcomes; registered served archive metadata is checked separately. No live provider validation.',samples:[],performance:[]};
 try{
 for(const config of [{width:1440,height:1000,scale:1},{width:390,height:844,scale:1},{width:320,height:844,scale:1},{width:720,height:500,scale:2}]){
 const context=await browser.newContext({viewport:{width:config.width,height:config.height},deviceScaleFactor:config.scale,reducedMotion:'reduce'}),page=await context.newPage(),errors=[];let fail=false,delay=0;const requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
 await context.route('https://**/*',async r=>{const u=r.request().url();if(u.includes('/v1/state/nfl'))return r.fulfill({json:{season:'2026',display_week:4,season_type:'regular'}});if(u.includes('/matchups/')){if(delay)await new Promise(resolve=>setTimeout(resolve,delay));return fail?r.fulfill({status:503,body:'Unavailable'}):r.fulfill({json:matchups});}return r.abort();});
 await context.route('**/data/ui/waivers/index.json',r=>r.fulfill({json:waiverIndex}));await context.route('**/data/ui/waivers/leagues/*.json',r=>r.fulfill({json:waiver(r.request().url().split('/').pop().replace('.json',''))}));
 await page.goto(url,{waitUntil:'load'});await page.waitForFunction(()=>window.FIEEditorial&&window.FIEPortfolioConfig.loaded&&!window.FIEPortfolio.refreshing);await inject(page);
 const shot=n=>page.screenshot({path:path.join(out,`${n}-${config.width}-${config.scale}x.png`),fullPage:true});const noOverflow=async()=>assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'viewport overflow');
 await page.getByText('Reported matchup result',{exact:true}).waitFor();assert(await page.getByRole('cell',{name:'0.00 pts',exact:true}).isVisible());await noOverflow();await shot('weekly');
 const formats=[];for(const format of ['REDRAFT','DYNASTY','REDRAFT_BESTBALL','DYNASTY_BESTBALL','CHOPPED','AUTO']){await page.evaluate(format=>{state.leagueRules.format=format;activateTab('startsit');},format);await page.getByRole('cell',{name:'Journey Zero',exact:true}).waitFor();if(format==='CHOPPED')assert(await page.getByText('League scoring / survival context',{exact:true}).isVisible());if(format.includes('BESTBALL'))assert(await page.getByRole('heading',{name:'Reported automatic contribution',exact:true}).isVisible());await noOverflow();formats.push(format);}
 await page.evaluate(()=>{state.leagueRules.format='REDRAFT';activateTab('myroster');});await page.getByRole('heading',{name:'Roster assets',exact:true}).waitFor();assert(await page.getByRole('rowheader',{name:/Journey Defender/}).isVisible());
 const expand=page.getByRole('button',{name:/Expand Journey Zero/}).first();await expand.focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#fieContextWorkspace .fie-expanded:visible').count(),1);
 const advanced=page.getByRole('button',{name:/Advanced evidence for Journey Zero/}).first();await advanced.focus();await page.keyboard.press('Enter');await page.locator('dialog[open]').waitFor();await page.keyboard.press('Tab');assert(await page.evaluate(()=>!!document.activeElement.closest('dialog[open]')),'Native reader traps keyboard focus');await page.keyboard.press('Escape');assert(await advanced.evaluate(e=>e===document.activeElement));
 // A nested source reader returns to its prior DOM and its original outer trigger.
 await page.evaluate(()=>{const outer=document.createElement('div'),inner=document.createElement('button');inner.textContent='Inspect nested source';inner.onclick=()=>FIEEditorial.openReader({title:'Nested source',entries:[['Value',0]]},inner);outer.append(inner);FIEEditorial.openReader({title:'Journey reader',content:outer},document.activeElement);});await page.getByRole('button',{name:'Inspect nested source',exact:true}).click();await page.getByRole('button',{name:'Back to previous details',exact:true}).click();assert(await page.getByRole('button',{name:'Inspect nested source',exact:true}).evaluate(e=>e===document.activeElement));await shot('nested-reader');await page.keyboard.press('Escape');assert(await advanced.evaluate(e=>e===document.activeElement));
 await advanced.click();await page.evaluate(()=>activateTab('team'));await page.waitForFunction(()=>!document.getElementById('fieEvidenceReader').open);assert.equal(await page.locator('.fie-expanded:visible').count(),0);
 await page.evaluate(()=>activateTab('waivers'));await page.getByText(/Blocked: no eligible waiver forecasts/).waitFor();await page.getByRole('button',{name:'Results',exact:true}).click();await page.waitForFunction(()=>location.hash.includes('waiver=results'));await page.getByRole('button',{name:'Market / Budget',exact:true}).click();await page.waitForFunction(()=>location.hash.includes('waiver=market'));await page.evaluate(()=>history.back());await page.waitForFunction(()=>window.FIEWaiverWorkspace.lens==='results');await page.getByRole('button',{name:'Evidence / Documents',exact:true}).click();await page.getByRole('heading',{name:'League evidence',exact:true}).waitFor();await shot('waiver-evidence');await noOverflow();
 await page.evaluate(()=>activateTab('startsit'));await page.locator('#weekSelect').selectOption('5');await page.getByRole('heading',{name:'Projected starters',exact:true}).waitFor();await page.locator('#weekSelect').selectOption('4');await page.locator('#weekSelect').selectOption('3');await page.getByText('Reported matchup result',{exact:true}).waitFor();
 fail=true;await page.getByRole('button',{name:'Refresh results',exact:true}).click();await page.getByText(/Matchup results unavailable: HTTP 503/).waitFor();await shot('error');fail=false;await page.getByRole('button',{name:'Refresh results',exact:true}).click();await page.getByText('Reported matchup result',{exact:true}).waitFor();
 // Namespace A→B→A and a late result following a change. Owners stay scoped.
 delay=100;await page.getByRole('button',{name:'Refresh results',exact:true}).click();await page.evaluate(id=>{dispatchEvent(new CustomEvent('fie:league-changing'));state.league={...state.league,league_id:id,name:'Fictional B'};document.getElementById('kLeague').textContent='Fictional B';activateTab('startsit');},other);await page.getByText('Reported matchup result',{exact:true}).waitFor();assert((await page.locator('#fieWeeklyWorkspace').innerText()).includes('Fictional B'));delay=0;await inject(page);await page.getByText('Reported matchup result',{exact:true}).waitFor();assert((await page.locator('#fieWeeklyWorkspace').innerText()).includes('999'));
 // Rejected history restore is recoverable without relabeling the current namespace.
 await page.evaluate(id=>{window.__qaController=window.FIELeagueController;window.FIELeagueController={switchLeague:async()=>{throw Error('Fictional offline load failure');}};location.hash='view=myroster&league='+id;},other);await page.locator('#fieRouteNotice').waitFor({state:'visible'});assert.equal(await page.evaluate(()=>String(state.league.league_id)),lid);await page.evaluate(()=>{window.FIELeagueController=window.__qaController;delete window.__qaController;});
 // Global index must not fetch inventories or documents until requested.
 const before=requests.length;await page.evaluate(()=>activateTab('reports'));await page.getByRole('heading',{name:'Document index',exact:true}).waitFor();assert.equal(await page.locator('#reportsPanel .fie-disclosure').first().getByRole('columnheader').count(),6,'Column headers remain in the mobile accessibility tree');assert(!requests.slice(before).some(u=>u.includes('/inventories/')||u.includes('/documents/')),'Basic Reports must not bulk-load evidence');assert(!await page.locator('#fieWeeklyWorkspace').isVisible());await noOverflow();await shot('reports');
 const measurements=await page.evaluate(()=>{const a=document.querySelector('.footer'),b=document.querySelector('#reportsPanel .fie-disclosure-heading p'),c=document.querySelector('#reportsPanel .fie-status');return [a,b,c].map(e=>({text:e.textContent.slice(0,70),color:getComputedStyle(e).color,background:getComputedStyle(e).backgroundColor,ancestorBackground:getComputedStyle(e.closest('.fie-disclosure')||document.body).backgroundColor}));});const ratios=measurements.map(m=>({...m,ratio:contrast(rgb(m.color),rgb(m.background).length===3&&!m.background.endsWith(', 0)')?rgb(m.background):rgb(m.ancestorBackground))}));assert(ratios.every(x=>x.ratio>=4.5),'Measured normal text contrast');
 await page.locator('.fie-skip-link').focus();await page.keyboard.press('Enter');assert(await page.locator('#sectionTitle').evaluate(e=>e===document.activeElement));assert(await page.locator('#primaryNav [data-section=reports]').getAttribute('aria-current')==='page');
 await context.unroute('**/data/ui/waivers/index.json');await page.locator('#reportsPanel summary').filter({hasText:'capture coverage and operations'}).click();await page.getByRole('heading',{name:'Captured waiver reports',exact:true}).waitFor();const realIndex=JSON.parse(fs.readFileSync(path.join(root,'data/ui/waivers/index.json')));assert.equal(await page.getByRole('heading',{name:'Captured waiver reports',exact:true}).locator('..').locator('..').locator('tbody tr:not(.fie-expanded)').count(),realIndex.portfolio_reports.length);await noOverflow();await shot('served-capture-metadata');
 assert.deepStrictEqual(errors,[],'Uncaught browser errors');report.samples.push({...config,zoom:config.scale===2?'200% equivalent CSS layout viewport (720 CSS px rendered to 1440 physical px); not native browser zoom':'100%',formats,status:'PASS',contrast:ratios,errors});await context.close();
 }
 // Fair cold/warm index comparison: same browser, viewport and blocked external requests.
 for(const [name,prefix] of [['phase06','/previous/'],['phase07','/']]){const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.route('https://**/*',r=>r.abort());const page=await context.newPage(),requests=[];page.on('request',r=>requests.push(r.url()));const start=Date.now();await page.goto(url+prefix,{waitUntil:'load'});await page.waitForFunction(()=>window.FIEReportsWorkspace&&window.FIEPortfolioConfig.loaded&&!window.FIEPortfolio.refreshing);const readyMs=Date.now()-start;const timings=[];for(let i=0;i<3;i++){await page.evaluate(()=>{FIEPortfolio.leave();activateTab('all');});const t=Date.now();await page.evaluate(()=>activateTab('reports'));await page.getByRole('heading',{name:'Document index',exact:true}).waitFor();timings.push(Date.now()-t);}const indexes=requests.filter(u=>u.includes('data/ui/reports/index.json')).length;assert.equal(indexes,1,'Shared index cached across navigation');assert(!requests.some(u=>u.includes('/inventories/')||u.includes('ui/reports/documents/')));report.performance.push({name,readyMs,reportColdMs:timings[0],reportWarmMs:timings.slice(1),indexRequests:indexes,conditions:'Single local run; identical viewport/browser, external requests blocked. Hardware timing is descriptive, not a universal speed claim.'});await context.close();}
 // Validate registered production archive derivatives actually served, not only source paths.
 const idx=JSON.parse(fs.readFileSync(path.join(root,'data/ui/reports/index.json')));const checks=[];for(const d of idx.documents){const r=await fetch(url+'/'+d.url);assert(r.ok);const x=await r.json();assert.equal(x.source.sha256,d.source.sha256);checks.push(d.id);}report.servedDocuments=checks;const realWaivers=JSON.parse(fs.readFileSync(path.join(root,'data/ui/waivers/index.json')));let captureRows=0;for(const [id,ref] of Object.entries(realWaivers.leagues)){const r=await fetch(url+'/'+ref);assert(r.ok);const x=await r.json();assert.equal(x.league_id,id);for(const captured of x.reports||[]){assert.equal(String(captured.report.league_id),id);assert(captured.source.path&&captured.source.sha256);assert(Number.isFinite(captured.season)&&Number.isFinite(captured.week));captureRows++;}}report.servedCaptures={leagues:Object.keys(realWaivers.leagues).length,rows:captureRows,status:'namespace and binding verified; no activation inferred'};report.status='PASS';fs.writeFileSync(path.join(out,'comparison.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
