/* Explicit fictional completed provider draft; current assets are intentionally different. */
'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const {chromium}=require(process.env.FIE_UI_PLAYWRIGHT||'playwright'),root=path.resolve(process.argv[2]||'dist'),out=path.resolve(process.env.FIE_UI_QA_OUTPUT||'editorial-draft-review-qa');fs.mkdirSync(out,{recursive:true});
(async()=>{
 const server=await new Promise(resolve=>{const s=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost'),f=path.resolve(root,'.'+(u.pathname==='/'?'/index.html':u.pathname));if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(f,(err,b)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':f.endsWith('.json')?'application/json':'text/html');res.end(b);});}).listen(0,'127.0.0.1',()=>resolve(s));});
 const browser=await chromium.launch({headless:true}),report={mode:'Fictional completed picks and deliberately distinct current roster in the real app; not live-league validation',samples:[]};
 try{for(const width of [1440,390,320,720]){
 const context=await browser.newContext({viewport:{width,height:1000}});await context.route('https://**/*',r=>r.abort());const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`,{waitUntil:'load'});await page.waitForFunction(()=>window.FIEDraftReviewWorkspace&&window.FIEPortfolioConfig.loaded&&!window.FIEPortfolio.refreshing);
 const provider=await page.evaluate(()=>{
  state.league={league_id:'fixture',name:'Fictional completed draft',season:'2026',status:'in_season',total_rosters:2,roster_positions:['QB','RB','WR','SUPER_FLEX','IDP_FLEX','BN'],scoring_settings:{pass_yd:.04,rec:1,tkl:1},settings:{type:0}};state.leagueRules={...state.leagueRules,format:'REDRAFT',allowedExperience:['R','Y2']};
  state.rosters=[{roster_id:1,owner_id:'one',players:['3000'],starters:['3000']},{roster_id:2,owner_id:'two',players:[],starters:[]}];state.users=[{user_id:'one',display_name:'Fictional A'},{user_id:'two',display_name:'Fictional B'}];state.selectedRoster=1;state.matched=true;
  PLAYERS=Array.from({length:90},(_,i)=>({sleeperId:String(1000+i),name:'Current '+i,position:['QB','RB','WR','LB'][i%4],side:i%4===3?'IDP':'OFF',team:'BUF',yearsExp:1,leagueEligible:true,availability:'FA',ownerRosterId:null,engineSeasonProjection:999-i,weeklyProjection:10,projectedVOR:50-i,currentOpportunity:60,targetScore:65,leagueFit:70,weeklyFloor:5,weeklyCeiling:20,marketADP:i===0?null:1+i,seasonScore:60,role:'Starter'}));
  PLAYERS.push({...PLAYERS[0],sleeperId:'3000',name:'Post-draft acquisition',ownerRosterId:1,availability:'OWNED'});state.projectionStatus={...state.projectionStatus,season:true,seasonCount:91};
  const draft={draft_id:'review',league_id:'fixture',season:'2026',status:'complete',type:'snake',last_picked:Date.UTC(2026,8,1),settings:{teams:2,rounds:45},slot_to_roster_id:{1:1,2:2},draft_order:{one:1,two:2}},picks=PLAYERS.slice(0,90).map((p,i)=>({pick_no:i+1,player_id:i===88?'missing':p.sleeperId,roster_id:i%2+1,round:Math.floor(i/2)+1,draft_slot:i%2+1,picked_by:i%2?'two':'one',metadata:i===88?{}:{first_name:'Recorded',last_name:String(i),position:p.position,amount:i===0?0:i}}));
  state.draftIntel={...state.draftIntel,loaded:true,loading:false,error:null,selectedDraftId:'review',draft,drafts:[draft],picks,tradedPicks:[]};state.draftContext={...state.draftContext,loaded:true};state.savedLeagues=[{id:'fixture',name:'Fictional completed draft',formatOverride:'AUTO'}];
  state.draftArchive={loaded:true,loading:false,updatedAt:'2026-09-02T12:00:00Z',errors:[],leagues:[],adpRows:{},drafts:['old-a','old-b'].map(draftId=>({draftId,leagueId:'older',leagueName:'Imported historical fixture',rootId:'fixture',season:2025,status:'complete',name:draftId,kind:'startup',profile:{format:'REDRAFT',teams:2,sf:true,idp:true,ppr:'PPR'},profileKey:'fixture-profile',settingsKey:'fixture-settings',users:{one:'Fictional A'},picks:[{playerId:'1000',pickNo:1,round:1,rosterId:1,pickedBy:'one',name:'Archived reference',position:'QB'}]}))};
  populateFilters();populateRosterPicker();populateDraftControls();FIEDraftBaseValueService.invalidate();FIEPortfolio.leave();activateTab('draftanalysis');return {draft,picks};
 });
 await context.route('https://api.sleeper.app/v1/**',r=>{const u=r.request().url(),body=u.endsWith('/drafts')?[provider.draft]:u.endsWith('/picks')?provider.picks:u.endsWith('/traded_picks')?[]:provider.draft;return r.fulfill({json:body});});
 const host=page.locator('#draftAnalysisSummary'),shot=n=>page.screenshot({path:path.join(out,`${n}-${width}.png`),fullPage:true}),overflow=async()=>assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Page horizontal overflow');
 await page.getByRole('heading',{name:'Your actual picks',exact:true}).waitFor();const own=host.locator('.fie-disclosure').first();assert.equal(await own.locator('tbody tr:not(.fie-expanded)').count(),20);assert.equal(await host.locator('.fie-expanded:visible').count(),0);assert(!/Post-draft acquisition|999\.0|TAKE NOW/.test(await host.innerText()));assert((await host.innerText()).includes('authentic pick-time alternatives'));assert.equal(await page.locator('.draft-history-toolbar:visible').count(),0);assert(await page.locator('#subnav').getByRole('button',{name:'Analysis / Review',exact:true}).count());await overflow();await shot('review-basic');
 await host.getByRole('button',{name:'Show 20 more',exact:true}).click(); await host.getByRole('button',{name:'Show 5 more',exact:true}).click();assert.equal(await own.locator('tbody tr:not(.fie-expanded)').count(),45);assert((await own.innerText()).includes('Unresolved missing'));assert(!/Current 0/.test(await own.innerText()));
 const parity=await page.evaluate(()=>[...document.querySelectorAll('#draftAnalysisSummary .fie-disclosure:first-of-type tbody tr:not(.fie-expanded)')].map((tr,i)=>({pick:tr.children[0].textContent,expected:String(state.draftIntel.picks.filter(p=>p.roster_id===1)[i].pick_no)})));for(const x of parity)assert.equal(x.pick,x.expected);
 await own.getByRole('button',{name:/Expand /}).first().click();assert((await own.innerText()).includes('Subsequent observed selections'));assert((await own.innerText()).includes('999.0 season points · current loaded forecast'));assert((await own.innerText()).includes('No authenticated pick-time reference'));await shot('pick-expanded');
 const advanced=own.getByRole('button',{name:/Advanced evidence/}).first();await advanced.click();await page.locator('dialog[open]').waitFor();assert((await page.locator('dialog[open]').innerText()).includes('Historical grade / counterfactual'));await shot('pick-advanced');await page.keyboard.press('Escape');assert(await advanced.evaluate(e=>e===document.activeElement));
 const player=own.getByRole('button',{name:'Current player details',exact:true}).first();await player.click();await page.locator('dialog[open]').waitFor();assert((await page.locator('dialog[open]').innerText()).includes('Current 0'));await page.keyboard.press('Escape');assert(await player.evaluate(e=>e===document.activeElement));
 await host.locator('summary').filter({hasText:'Drafted allocation'}).click();await page.getByRole('heading',{name:'Observed positional allocation',exact:true}).waitFor();await host.getByRole('button',{name:'Advanced · Structural assignment and limitations',exact:true}).click();await page.locator('dialog[open]').waitFor();assert((await page.locator('dialog[open]').innerText()).includes('One per filled starter slot'));assert(!/Post-draft acquisition/.test(await page.locator('dialog[open]').innerText()));await page.keyboard.press('Escape');await shot('construction');
 await page.getByRole('combobox',{name:'Review roster',exact:true}).selectOption('2');assert.equal(await host.locator('.fie-disclosure').first().locator('tbody tr:not(.fie-expanded)').first().locator('th').innerText(),'2');await page.getByRole('combobox',{name:'Review roster',exact:true}).selectOption('1');
 await host.locator('summary').filter({hasText:'Imported draft archive'}).click();await page.getByRole('heading',{name:'Imported draft records',exact:true}).waitFor();await host.getByRole('button',{name:'Advanced · Original cross-league diagnostics',exact:true}).click();await page.locator('.draft-history-table').first().waitFor();assert((await page.locator('#fieReviewLegacyReturn').innerText()).includes('lack authenticated pick-time cutoffs'));await page.getByRole('button',{name:'Back to Basic draft review',exact:true}).click();await page.getByRole('heading',{name:'Your actual picks',exact:true}).waitFor();assert.equal(await page.locator('.draft-history-toolbar:visible').count(),0);
 await host.locator('summary').filter({hasText:'Current repair workspace'}).click();await host.getByRole('button',{name:'Open current roster',exact:true}).click();await page.getByRole('heading',{name:'Roster assets',exact:true}).waitFor();assert((await page.locator('#fieContextWorkspace').innerText()).includes('Post-draft acquisition'));await page.evaluate(()=>activateTab('draftassistant'));await page.getByRole('heading',{name:'Your actual picks',exact:true}).waitFor();assert.equal(await page.locator('#draftAssistantPanel:visible').count(),0);
 await page.evaluate(()=>activateTab('valuefinder'));await page.getByRole('heading',{name:'Current league value reference',exact:true}).waitFor();const values=page.locator('#valueFinderSummary');assert(!/TAKE NOW|survive|Current pick/.test(await values.innerText()));await page.evaluate(()=>renderValueFinder());await page.getByRole('heading',{name:'Current league value reference',exact:true}).waitFor();await overflow();await shot('current-values');
 await page.evaluate(()=>{state.draftIntel.draft.type='auction';activateTab('draftanalysis');});await page.getByRole('columnheader',{name:'Auction cost',exact:true}).waitFor();assert.equal(await host.locator('.fie-disclosure').first().locator('tbody tr:not(.fie-expanded)').first().locator('td').nth(2).innerText(),'0.0 · provider units');await shot('auction-zero');
 for(const [kind,label]of [['foreign','does not match'],['season','does not match'],['draft','does not match'],['loading','Refreshing'],['error','refresh failed']]){await page.evaluate(kind=>{if(kind==='foreign')state.draftIntel.draft.league_id='other';if(kind==='season')state.draftIntel.draft.season='2025';if(kind==='draft')state.draftIntel.selectedDraftId='other';if(kind==='loading')state.draftIntel.loading=true;if(kind==='error')state.draftIntel.error='fixture';render();},kind);assert((await host.innerText()).includes(label));assert.equal(await page.getByRole('heading',{name:'Your actual picks',exact:true}).count(),0);await page.evaluate(()=>{state.draftIntel.loading=false;state.draftIntel.selectedDraftId='review';});await page.evaluate(()=>loadDraftIntel());}
 await page.evaluate(()=>{state.draftIntel.picks[1].pick_no=3;render();});assert((await host.innerText()).includes('Observed ledger warning'));await host.locator('summary').filter({hasText:'Drafted allocation'}).click();await host.getByText('Slot analysis withheld because the observed ledger is conflicting or incomplete.',{exact:true}).waitFor();await page.evaluate(()=>loadDraftIntel());
 for(const format of ['DYNASTY','REDRAFT_BESTBALL','DYNASTY_BESTBALL','CHOPPED','CHOPPED_BESTBALL']){await page.evaluate(f=>{state.leagueRules.format=f;activateTab('draft');},format);await page.getByRole('heading',{name:'Observed league results',exact:true}).waitFor();await overflow();}
 await page.evaluate(()=>{state.draftIntel.draft.status='pre_draft';state.draftIntel.picks=[];activateTab('draftassistant');});await page.getByRole('heading',{name:'Top Picks',exact:true}).waitFor();assert.equal(await page.locator('#draftAnalysisPanel:visible').count(),0);await page.evaluate(()=>{state.draftIntel.draft.status='drafting';state.draftIntel.picks=[{pick_no:1,player_id:'1000',roster_id:1,draft_slot:1}];activateTab('draftassistant');});await page.getByRole('heading',{name:'Live Draft Assistant',exact:true}).waitFor();assert.equal(await page.locator('#draftAnalysisPanel:visible').count(),0);
 assert.deepStrictEqual(errors,[],'Uncaught browser errors');report.samples.push({width,status:'PASS',errors});await context.close();
 }report.status='PASS';fs.writeFileSync(path.join(out,'comparison.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));}finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
