/* Populated offline real-app waiver review; explicit fictional data, not live league validation. */
'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');const {chromium}=require(process.env.FIE_UI_PLAYWRIGHT||'playwright');
const root=path.resolve(process.argv[2]||'dist'),out=path.resolve(process.env.FIE_UI_QA_OUTPUT||'editorial-waiver-qa');fs.mkdirSync(out,{recursive:true});
const lid='999999999999999999';
const winner={transaction_id:'qa-win',roster_id:2,status:'complete',bid:0,manager_name:'Fictional opponent',manager_identity_status:'RESOLVED'};
const failed={transaction_id:'qa-failed',roster_id:1,status:'failed',bid:0,manager_name:'Your fictional team',failure_metadata:{notes:'This player was claimed by another owner.'},is_explicit_competitive_loss:false};
const row={player_id:'2001',player_name:'Casey River',position:'RB',source_league_id:lid,season:2026,week:3,winning_claims:[winner],managed_user_claims:[failed],other_observed_failed_claims:[failed],visibility:'PARTIAL_OBSERVED',visibility_note:'Absent private claims remain unknown.'};
const data={league_id:lid,reporting_only:true,reports:[{season:2026,week:3,captured_at:'2026-09-20T12:00:00Z',capture_id:'fictional-qa',source:{path:'fictional/qa.json',sha256:'qa-only'},report:{league_id:lid,status:'BLOCKED_NO_ELIGIBLE_WAIVER_PROJECTIONS',research_only:true,source_health_reason:'No activated forecast'}}],history:[{captured_at:'2026-09-20T12:00:00Z',source:{path:'fictional/history.json',sha256:'qa-only'},ledger:[row,{...row,player_id:'2002',player_name:'Multiple acquisition player',winning_claims:[winner,{...winner,transaction_id:'qa-second',roster_id:1,bid:4,manager_name:'Your fictional team'}],managed_user_claims:[],other_observed_failed_claims:[]},{...row,season:2025,player_name:'Wrong season should never appear'},{...row,source_league_id:'prior',player_name:'Wrong league should never appear'}]}]};
(async()=>{
const server=await new Promise(resolve=>{const s=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost'),f=path.resolve(root,'.'+(u.pathname==='/'?'/index.html':u.pathname));if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(f,(err,b)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':f.endsWith('.json')?'application/json':'text/html');res.end(b);});}).listen(0,'127.0.0.1',()=>resolve(s));});
const browser=await chromium.launch({headless:true}),report={mode:'Fictional provider and archived-report fixtures in the real app. Not live league validation.',samples:[]};
try{for(const width of [1440,390]){
 const context=await browser.newContext({viewport:{width,height:width===390?844:1000}}),page=await context.newPage();let fail=false,delay=0;
 await context.route('https://**/*',r=>r.abort());await context.route('**/data/ui/waivers/**',async r=>{const u=r.request().url();if(fail)return r.fulfill({status:503,body:'Unavailable'});if(u.endsWith('/index.json'))return r.fulfill({json:{leagues:{[lid]:`data/ui/waivers/leagues/${lid}.json`},documents:[{title:'Shared waiver methodology',url:'data/ui/waivers/documents/qa.json'}]}});if(u.includes('/documents/'))return r.fulfill({json:{title:'Shared waiver methodology',scope:'Overarching · all leagues',source:{path:'fictional/method.md',sha256:'qa-only'},text:'# Shared document\n<script>window.qaInjected=true</script>'}});if(delay)await new Promise(x=>setTimeout(x,delay));return r.fulfill({json:data});});
 await context.route('**/data/ui/reports/index.json',r=>r.fulfill({json:{schema:'fie-editorial-reports-v1',reporting_only:true,documents:[{id:'qa',title:'Shared waiver methodology',url:'data/ui/waivers/documents/qa.json',scope:'Overarching · all leagues',period:'Fictional reference',status:'Reference document'}],inventories:[]}}));
 await page.goto(`http://127.0.0.1:${server.address().port}`,{waitUntil:'load'});await page.waitForFunction(()=>!!window.FIEWaiverWorkspace&&!!window.FIEUX93);
 await page.evaluate(()=>{state.league={league_id:'999999999999999999',name:'Fictional waiver league',season:'2026',roster_positions:['QB','RB','WR','TE','BN'],scoring_settings:{rec:1},settings:{type:0,best_ball:0,waiver_budget:100}};state.rosters=[{roster_id:1,owner_id:'one',players:['1001'],settings:{waiver_budget_used:0}},{roster_id:2,owner_id:'two',players:[],settings:{waiver_budget_used:100}},{roster_id:3,owner_id:'three',players:[],settings:{}}];state.users=[{user_id:'one',display_name:'Your fictional team'},{user_id:'two',display_name:'Fictional opponent'},{user_id:'three',display_name:'Missing budget manager'}];PLAYERS=[{sleeperId:'2001',name:'Casey River',position:'RB',team:'BUF',availability:'FA',leagueEligible:true,yearsExp:1,side:'OFF',waiver_forecast_eligible:false},{sleeperId:'2002',name:'Jordan Quinn',position:'WR',team:'BUF',availability:'FA',leagueEligible:true,yearsExp:1,side:'OFF'}];state.selectedRoster=1;state.matched=true;state.weekly={...state.weekly,season:2026,week:3,loaded:true};populateRosterPicker();document.getElementById('kLeague').textContent='Fictional waiver league';document.getElementById('status').textContent='Fictional browser test data · not live claims';document.getElementById('weekSelect').value='3';FIEPortfolio.leave();activateTab('waivers');});
 await page.getByText(/Blocked: no eligible waiver forecasts/).waitFor();assert(await page.getByRole('rowheader',{name:'Casey River',exact:true}).isVisible());
 const basic=await page.evaluate(()=>({firstRowTop:document.querySelector('#fieWaiverWorkspace table tbody tr')?.getBoundingClientRect().top,documentWidth:document.documentElement.scrollWidth,viewport:innerWidth}));assert(basic.documentWidth<=width+1,'No viewport overflow');await page.screenshot({path:path.join(out,`watchlist-${width}.png`),fullPage:true});console.log('Basic measurement',width,basic);assert(basic.firstRowTop+35<(width===390?844:1000),'First basic player row in first viewport');await page.screenshot({path:path.join(out,`watchlist-${width}.png`),fullPage:true});
 await page.getByRole('button',{name:'Expand Casey River',exact:true}).click();assert(await page.locator('.fie-expanded:visible').getByText(/no supported bid curve served/).isVisible());await page.screenshot({path:path.join(out,`expanded-${width}.png`),fullPage:true});
 await page.locator('#fieWaiverWorkspace summary').filter({hasText:'Existing browser comparisons'}).click();await page.getByRole('heading',{name:'Existing browser add/drop comparisons',exact:true}).waitFor();assert(!(await page.locator('#fieWaiverWorkspace').innerText()).includes('Suggested FAAB'));await page.screenshot({path:path.join(out,`legacy-comparison-${width}.png`),fullPage:true});
 const adv=page.getByRole('button',{name:'Advanced evidence for Casey River',exact:true});await adv.click();assert(await page.getByText('Forecast gate',{exact:true}).isVisible());assert(await page.getByText('Source blocked',{exact:true}).isVisible());await page.screenshot({path:path.join(out,`advanced-${width}.png`),fullPage:true});await page.keyboard.press('Escape');assert(await adv.evaluate(e=>document.activeElement===e));
 await page.getByRole('button',{name:'Results',exact:true}).click();await page.getByRole('heading',{name:'Observed waiver results',exact:true}).waitFor();assert(await page.getByRole('cell',{name:/0 · Failed · reason in details/}).isVisible());assert(await page.getByRole('cell',{name:/2 acquisitions · expand/}).isVisible());assert(!(await page.getByText('Wrong season should never appear',{exact:true}).count()));assert(!(await page.getByText('Wrong league should never appear',{exact:true}).count()));assert.strictEqual(await page.locator('#fieWaiverWorkspace .fie-expanded:visible').count(),0);
 await page.getByRole('button',{name:'Expand Casey River',exact:true}).click();assert(await page.locator('.fie-expanded:visible').getByText(/This player was claimed by another owner/).isVisible());assert(!(await page.locator('#fieWaiverWorkspace').innerText()).includes('outbid'));await page.screenshot({path:path.join(out,`results-${width}.png`),fullPage:true});
 await page.locator('#weeklyRosterPicker').selectOption('2');await page.getByRole('cell',{name:/0 · Acquired/}).first().waitFor();assert.strictEqual(await page.locator('#fieWaiverWorkspace .fie-expanded:visible').count(),0);
 await page.getByRole('button',{name:'Market / Budget',exact:true}).click();await page.getByRole('heading',{name:'Manager budgets',exact:true}).waitFor();assert((await page.locator('#fieWaiverWorkspace').innerText()).includes('cap less used 0'));assert(await page.getByRole('rowheader',{name:'Missing budget manager',exact:true}).isVisible());await page.screenshot({path:path.join(out,`market-${width}.png`),fullPage:true});
 await page.getByRole('button',{name:'Evidence / Documents',exact:true}).click();await page.getByRole('button',{name:'Shared waiver methodology',exact:true}).click();await page.getByText('Overarching · all leagues',{exact:true}).waitFor();assert(!(await page.evaluate(()=>window.qaInjected)));await page.screenshot({path:path.join(out,`documents-${width}.png`),fullPage:true});await page.keyboard.press('Escape');
 await page.locator('#weekSelect').selectOption('4');await page.getByRole('cell',{name:/Unavailable/}).first().waitFor();await page.getByRole('button',{name:'Results',exact:true}).click();await page.getByText(/No observed ledger is served/).waitFor();await page.screenshot({path:path.join(out,`missing-period-${width}.png`),fullPage:true});
 await page.locator('#weekSelect').selectOption('3');await page.getByRole('heading',{name:'Observed waiver results',exact:true}).waitFor();fail=true;await page.getByRole('button',{name:'Reload archived evidence',exact:true}).click();await page.getByText(/Archived evidence unavailable: HTTP 503/).waitFor();await page.screenshot({path:path.join(out,`unavailable-${width}.png`),fullPage:true});fail=false;await page.getByRole('button',{name:'Reload archived evidence',exact:true}).click();await page.getByRole('heading',{name:'Observed waiver results',exact:true}).waitFor();
 await page.getByRole('button',{name:'Market / Budget',exact:true}).click();await page.waitForFunction(()=>location.hash.includes('waiver=market'));await page.evaluate(()=>history.back());await page.getByRole('heading',{name:'Observed waiver results',exact:true}).waitFor();
 delay=300;await page.getByRole('button',{name:'Reload archived evidence',exact:true}).click();await page.evaluate(()=>{window.dispatchEvent(new Event('fie:league-changing'));state.league={...state.league,league_id:'888888888888888888',name:'Other league'};FIEWaiverWorkspace.render();});await page.getByText(/No archived waiver evidence served for this league/).waitFor();await page.waitForTimeout(400);assert(!(await page.getByRole('rowheader',{name:'Casey River',exact:true}).count()));
 await page.evaluate(()=>activateTab('all'));await page.waitForFunction(()=>!document.body.classList.contains('fie-waiver-active'));assert(!(await page.locator('#fieWaiverWorkspace').isVisible()));report.samples.push({width,...basic});await context.close();
 }report.status='PASS';fs.writeFileSync(path.join(out,'comparison.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));}finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
