/* Explicit fictional fixtures in the real app; no live-league validation. */
'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const {chromium}=require(process.env.FIE_UI_PLAYWRIGHT||'playwright');
const root=path.resolve(process.argv[2]||'dist'),out=path.resolve(process.env.FIE_UI_QA_OUTPUT||'editorial-draft-preparation-qa');fs.mkdirSync(out,{recursive:true});
(async()=>{const server=await new Promise(resolve=>{const s=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost'),f=path.resolve(root,'.'+(u.pathname==='/'?'/index.html':u.pathname));if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(f,(err,b)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':f.endsWith('.json')?'application/json':'text/html');res.end(b);});}).listen(0,'127.0.0.1',()=>resolve(s));});
 const browser=await chromium.launch({headless:true}),report={mode:'Fictional loaded browser/provider records in the real application. Not live league validation.',samples:[]};try{for(const width of [1440,390,320,720]){
 const context=await browser.newContext({viewport:{width,height:1000}});await context.route('https://**/*',r=>r.abort());const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`,{waitUntil:'load'});await page.waitForFunction(()=>window.FIEContextWorkspace&&window.FIEPortfolioConfig.loaded&&!window.FIEPortfolio.refreshing);
 await page.evaluate(()=>{
 state.league={league_id:'fixture',name:'Fictional preparation league',season:'2026',status:'pre_draft',total_rosters:2,roster_positions:['QB','RB','WR','SUPER_FLEX','IDP_FLEX','BN'],scoring_settings:{pass_yd:.04,rec:1,tkl:1},settings:{type:0}};
 state.rosters=[{roster_id:1,owner_id:'one',players:[],starters:[]},{roster_id:2,owner_id:'two',players:[],starters:[]}];state.users=[{user_id:'one',display_name:'Fictional A'},{user_id:'two',display_name:'Fictional B'}];state.selectedRoster=1;state.matched=true;state.leagueRules={...state.leagueRules,format:'REDRAFT',allowedExperience:['R','Y2']};
 PLAYERS=Array.from({length:45},(_,i)=>({sleeperId:String(1000+i),name:'Preparation '+String(i).padStart(2,'0'),position:['QB','RB','WR','LB'][i%4],side:i%4===3?'IDP':'OFF',team:'BUF',yearsExp:1,leagueEligible:true,availability:'FA',ownerRosterId:null,engineSeasonProjection:i===0?0:200-i,weeklyProjection:10-i/10,projectedVOR:i===0?0:50-i,currentOpportunity:60,targetScore:65,leagueFit:70,weeklyFloor:5,weeklyCeiling:20,marketADP:i===0?null:20+i*5,seasonScore:60,role:'Starter',depthChartOrder:1,injuryStatus:'Healthy'}));
 PLAYERS.push({...PLAYERS[1],sleeperId:'999',name:'Ineligible veteran',leagueEligible:false,yearsExp:20});
 state.projectionStatus={...state.projectionStatus,season:true,seasonCount:45};const draft={draft_id:'prep',league_id:'fixture',season:'2026',status:'pre_draft',type:'snake',settings:{teams:2,rounds:15},slot_to_roster_id:{1:1,2:2},draft_order:{one:1,two:2}};state.draftIntel={...state.draftIntel,loaded:true,loading:false,error:null,selectedDraftId:'prep',draft,drafts:[draft],picks:[]};
 populateFilters();populateRosterPicker();populateDraftControls();document.getElementById('searchFilter').value='';document.getElementById('posFilter').value='ALL';FIEDraftBaseValueService.invalidate();FIE_VALUE_FINDER.invalidate('fixture');state.valueFinder={...state.valueFinder,band:'ALL',position:'ALL',experience:'ALL',snap:'ALL',confidence:'ALL',undervaluedOnly:false,availableOnly:false,limit:10};FIEPortfolio.leave();activateTab('draftassistant');
 });
 const host=page.locator('#draftAssistantSummary');const shot=async n=>page.screenshot({path:path.join(out,`${n}-${width}.png`),fullPage:true});const noOverflow=async()=>{const ok=await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1);if(!ok){console.log(await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+2).slice(0,15).map(e=>({id:e.id,cls:e.className,right:e.getBoundingClientRect().right,width:e.getBoundingClientRect().width}))));await shot('overflow');}assert(ok,'Page horizontal overflow');};
 await page.getByRole('heading',{name:'Top Picks',exact:true}).waitFor();assert.equal(await host.locator('.fie-expanded:visible').count(),0);assert.equal(await host.locator('tbody tr:not(.fie-expanded)').count(),5);assert(!await host.getByText('Ineligible veteran',{exact:true}).count());await noOverflow();await shot('assistant-basic');
 await host.getByRole('button',{name:/Expand /}).first().click();await host.locator('.fie-expanded:visible').getByText('Conditional opening target',{exact:true}).waitFor();await shot('assistant-expanded');const fit=host.locator('.fie-expanded:visible').getByRole('button',{name:'Further details · Existing roster and timing inputs',exact:true});await fit.click();await page.locator('dialog[open]').waitFor();assert((await page.locator('dialog[open]').innerText()).includes('Existing draft owner utility'));await page.keyboard.press('Escape');assert(await fit.evaluate(e=>e===document.activeElement));
 const advanced=host.getByRole('button',{name:/Advanced /}).first();await advanced.click();await page.locator('dialog[open]').waitFor();assert((await page.locator('dialog[open]').innerText()).includes('Base value is an index'));await shot('candidate-advanced');await page.keyboard.press('Escape');assert(await advanced.evaluate(e=>e===document.activeElement));
 await page.locator('#draftRosterPicker').selectOption('2');assert((await host.innerText()).includes('Provider slot 2'));await page.locator('#draftRosterPicker').selectOption('1');
 await host.locator('summary').filter({hasText:'Roster construction'}).click();await page.getByRole('heading',{name:'Roster slot requirements',exact:true}).waitFor();await shot('construction');
 await page.evaluate(()=>activateTab('draft'));await page.getByRole('heading',{name:'Draft reference board',exact:true}).waitFor();const board=page.locator('#fieDraftPreparation');assert.equal(await board.locator('tbody tr:not(.fie-expanded)').count(),40);await board.getByRole('button',{name:'Show 5 more',exact:true}).click();assert.equal(await board.locator('tbody tr:not(.fie-expanded)').count(),45);
 const parity=await page.evaluate(()=>{const owner=FIEDraftBaseValueService.rows().filter(x=>isLeagueEligible(x.p)).sort((a,b)=>a.overallRank-b.overallRank);return [...document.querySelectorAll('#fieDraftPreparation tbody tr:not(.fie-expanded)')].map((tr,i)=>({rank:tr.children[0].textContent,value:tr.children[3].textContent,expectedRank:String(owner[i].overallRank),expectedValue:Number(owner[i].baseValue).toFixed(1)}));});for(const x of parity){assert.equal(x.rank,x.expectedRank);assert.equal(x.value,x.expectedValue);}await noOverflow();await shot('board');
 await page.locator('#searchFilter').fill('Preparation 00');await page.waitForFunction(()=>document.querySelectorAll('#fieDraftPreparation tbody tr:not(.fie-expanded)').length===1);assert((await board.innerText()).includes('0.0 points')===false);await board.getByRole('button',{name:/Expand /}).click();assert((await board.innerText()).includes('0.0 points'));await page.locator('#searchFilter').fill('');
 await page.evaluate(()=>activateTab('all'));await page.getByRole('heading',{name:'Player explorer',exact:true}).waitFor();assert(!await board.isVisible());
 await page.evaluate(()=>activateTab('valuefinder'));await page.getByRole('heading',{name:'Market values',exact:true}).waitFor();const values=page.locator('#valueFinderSummary');assert.equal(await values.locator('.fie-expanded:visible').count(),0);assert(!/TAKE NOW/.test(await values.innerText()));await noOverflow();await shot('values-basic');
 await page.getByRole('combobox',{name:'Market range',exact:true}).selectOption('200_PLUS');await page.getByRole('heading',{name:'Market values',exact:true}).waitFor();await page.getByRole('combobox',{name:'Market range',exact:true}).selectOption('LT100');await values.getByRole('button',{name:'Advanced · Existing pick optimizer and scenarios',exact:true}).click();await page.locator('.vf-table').waitFor();assert((await values.innerText()).includes('Live pick context'));await page.getByRole('button',{name:'Back to Basic preparation',exact:true}).click();await page.getByRole('heading',{name:'Market values',exact:true}).waitFor();await shot('values-return');
 await page.evaluate(()=>{state.draftIntel.draft.league_id='other';activateTab('draftassistant');});assert.equal(await host.locator('tbody tr:not(.fie-expanded)').count(),0);assert((await host.innerText()).includes('does not match'));await page.evaluate(()=>activateTab('valuefinder'));assert.equal(await values.locator('tbody tr:not(.fie-expanded)').count(),0);
 await page.evaluate(()=>{state.draftIntel.draft.league_id='fixture';state.draftIntel.draft.status='drafting';activateTab('draftassistant');});assert.equal(await page.getByRole('heading',{name:'Top Picks',exact:true}).count(),0);assert.equal(await page.locator('#draftAssistantPanel h2').first().innerText(),'Live Draft Assistant');
 await page.evaluate(()=>{state.draftIntel.draft.status='complete';activateTab('draftassistant');});assert.equal(await page.getByRole('heading',{name:'Top Picks',exact:true}).count(),0);
 await page.evaluate(()=>{state.draftIntel.loaded=false;state.draftIntel.draft=null;activateTab('draftassistant');});await page.getByRole('heading',{name:'Top Picks',exact:true}).waitFor();assert((await host.innerText()).includes('Slot unknown'));await shot('unknown-state');await page.evaluate(()=>activateTab('valuefinder'));await values.getByRole('button',{name:'Advanced · Existing pick optimizer and scenarios',exact:true}).click();await page.locator('#vfPlanPick').waitFor();await page.locator('#vfPlanPick').fill('7');await page.locator('#vfPlanPick').dispatchEvent('change');assert.equal(await page.locator('#vfPlanPick').inputValue(),'7');await page.getByRole('button',{name:'Back to Basic preparation',exact:true}).click();
 for(const format of ['DYNASTY','REDRAFT_BESTBALL','DYNASTY_BESTBALL','CHOPPED']){await page.evaluate(f=>{state.leagueRules.format=f;FIEDraftBaseValueService.invalidate();activateTab('draft');},format);await page.getByRole('heading',{name:'Draft reference board',exact:true}).waitFor();await noOverflow();}
 assert.deepStrictEqual(errors,[],'Uncaught browser errors');report.samples.push({width,status:'PASS',errors});await context.close();
 }report.status='PASS';fs.writeFileSync(path.join(out,'comparison.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
