/* Display semantics and preservation of existing service outputs. */
'use strict';
const assert=require('assert'),vm=require('vm'),fs=require('fs');
const state={league:{league_id:'fixture',season:'2026',scoring_settings:{pass_yd:.04,unknown_bonus:5}},weekly:{season:2026,week:5},rosters:[]};
const window={state,currentWeek:()=>5,FIEScoringSupport:{audit:()=>({unsupported:['unknown_bonus'],nonlinear:[]})},tradeAssetValue:p=>p.asset,pickValue:p=>p.asset,rosterUtilityFromPool:pool=>({total:pool.reduce((s,p)=>s+p.utility,0),starterTotal:pool.reduce((s,p)=>s+p.utility,0)})};
const document={getElementById:()=>null,body:{classList:{toggle(){}}}};
vm.runInNewContext(fs.readFileSync('app/ui/context-workspace.js','utf8'),{window,document,console});
const ui=window.FIEContextWorkspace;
assert.strictEqual(ui.projection({engineSeasonProjection:0,sleeperSeasonProjection:123}).value,0);
assert.strictEqual(ui.projection({engineSeasonProjection:null,sleeperSeasonProjection:0}).value,0);
assert.strictEqual(ui.projection({engineSeasonProjection:null,sleeperSeasonProjection:null}).value,null);
assert.strictEqual(ui.projection({engineSeasonProjection:true}).value,null);
assert.strictEqual(ui.providerPoints({fpts:0,fpts_decimal:0}),0);
assert.strictEqual(ui.providerPoints({fpts:100,fpts_decimal:25}),100.25);
assert.strictEqual(ui.providerPoints({}),null);
assert.strictEqual(ui.providerPoints({fpts:null,fpts_decimal:25}),null);
assert.match(ui.ruleExample('pass_yd',.04),/0.40/);
assert.match(ui.ruleExample('unknown_bonus',5),/No generic linear example/);
assert.strictEqual(ui.scoringRows().find(x=>x.title==='Unknown Bonus').support,'Unsupported');
const pA={sleeperId:'a',utility:10,asset:20},pB={sleeperId:'b',utility:30,asset:40};
ui.render('noop',{rosterPool:rid=>rid===1?[pA]:[pB]});
const withPick=ui.tradeEffects(1,2,[pA],[pB],[{asset:7}],[]);
assert.strictEqual(withPick[0].before.total,10);assert.strictEqual(withPick[0].after.total,30);
assert.strictEqual(withPick[1].before.total,30);assert.strictEqual(withPick[1].after.total,10);
assert.strictEqual(withPick[0].asset,13);assert.strictEqual(withPick[1].asset,-13);
const withoutPick=ui.tradeEffects(1,2,[pA],[pB],[],[]);
assert.strictEqual(withPick[0].after.total,withoutPick[0].after.total,'Future picks must not enter immediate roster utility');
assert.strictEqual(withPick[1].after.total,withoutPick[1].after.total);
console.log('PASS editorial context: missing/zero, scoring interpretation, two-sided canonical utility and separate pick index.');
