'use strict';
const assert=require('assert'),vm=require('vm'),fs=require('fs');
const state={league:{league_id:'a',season:'2026'},selectedRoster:1,rosters:[{roster_id:1,owner_id:'owner'}],draftIntel:{loaded:true,selectedDraftId:'d',draft:{draft_id:'d',league_id:'a',season:'2026',status:'pre_draft',slot_to_roster_id:{3:1}},picks:[]}};
const window={state},document={getElementById:()=>null,body:{classList:{toggle(){}}}};
vm.runInNewContext(fs.readFileSync('app/ui/draft-preparation-workspace.js','utf8'),{window,document,console});const u=window.FIEDraftPreparationWorkspace;
assert.equal(u.lifecycle().mode,'pre');assert.equal(u.slot(),3);
state.draftIntel.draft.status='complete';assert.equal(u.lifecycle().mode,'post');
state.draftIntel.draft.status='pre_draft';state.draftIntel.picks=[{player_id:'p'}];assert.equal(u.lifecycle().mode,'live');
state.draftIntel.picks=[];state.draftIntel.draft.league_id='b';assert.equal(u.lifecycle().mode,'blocked');assert.equal(u.slot(),null);
state.draftIntel.draft.league_id='a';state.draftIntel.draft.season='2025';assert.equal(u.lifecycle().mode,'blocked');
state.draftIntel.draft.season='2026';state.draftIntel.selectedDraftId='other';assert.equal(u.lifecycle().mode,'blocked');
state.draftIntel.selectedDraftId='d';state.draftIntel.loading=true;assert.equal(u.lifecycle().mode,'unavailable');assert.equal(u.slot(),null);
state.draftIntel.loading=false;state.draftIntel.error='failed';assert.equal(u.lifecycle().mode,'unavailable');
state.draftIntel.error=null;state.draftIntel.draft.slot_to_roster_id={};state.draftIntel.draft.draft_order={owner:2};assert.equal(u.slot(),2);
state.draftIntel.draft.draft_order={};assert.equal(u.slot(),null);
const row=u.boardRow({overallRank:1,positionRank:1,tier:1,baseValue:0,p:{name:'Zero',marketADP:0,engineSeasonProjection:0,projectedVOR:0}});assert.equal(row.value,'0.0');assert.equal(row.market,'Unavailable');assert.match(row.expanded.find(x=>x[0]==='Season projection')[1],/^0.0 points/);
assert.equal(u.boardRow({p:{name:'Missing'},baseValue:null}).value,'Unavailable');
const cyclic={name:'Shared player'};cyclic.reference=cyclic;assert.doesNotThrow(()=>u.boardRow({p:cyclic}));
console.log('Editorial pre-draft display contract PASS');
