'use strict';
const fs = require('fs'), vm = require('vm'), assert = require('assert');
const fake = { readyState: 'loading', addEventListener() {}, getElementById() { return null; } };
const window = { state: { league: { roster_positions: ['QB','RB','FLEX','BN'] }, playerMap: {} }, addEventListener() {}, FIECore: { PlayerIdentity: { resolve: id => ({ status:'resolved',player:{name:`Player ${id}`,position:'QB'} }) }, PositionRegistry: { starterSlots: () => ['QB','RB','FLEX'] } } };
vm.runInNewContext(fs.readFileSync('app/ui/weekly-workspace.js','utf8'), { window, document: fake, Intl, Date, setTimeout, clearTimeout, MutationObserver: class {}, fetch() { throw Error('Unit test must not fetch'); } });
const w = window.FIEWeeklyWorkspace, c = { season: 2026, week: 3 };
assert.strictEqual(w.period(c, {season:2026,display_week:4,season_type:'regular'},[]), 'completed');
assert.strictEqual(w.period(c, {season:2026,display_week:2,season_type:'regular'},[]), 'upcoming');
assert.strictEqual(w.period(c, null, []), 'unknown');
assert.strictEqual(w.period(c, {season:2026,display_week:3,season_type:'pre'},[]), 'unknown');
assert.strictEqual(w.kickoff({gameday:'2026-10-04',gametime:'13:00'}), Date.parse('2026-10-04T17:00:00Z'));
assert.strictEqual(w.kickoff({gameday:'2026-12-06',gametime:'13:00'}), Date.parse('2026-12-06T18:00:00Z'));
assert.strictEqual(w.period(c,null,[{kickoff:'2026-09-20T17:00:00Z'}],Date.parse('2026-09-20T18:00:00Z')), 'live');
const rows = w.reportedPlayers({starters:['a','b','0'],starters_points:[0,null,0],players_points:{b:-2.5}});
assert.strictEqual(rows[0].actual,0,'Real zero preserved'); assert.strictEqual(rows[1].actual,-2.5,'Negative scoring preserved'); assert.strictEqual(rows[2].empty,true);
assert.strictEqual(w.reportedPlayers({starters:['a'],starters_points:[null]})[0].actual,null,'Missing is not zero');
assert.strictEqual(w.pairing([{roster_id:1,matchup_id:0},{roster_id:2,matchup_id:0}],'1').opponent.roster_id,2,'Zero matchup IDs valid');
assert.strictEqual(w.pairing([{roster_id:1,matchup_id:3},{roster_id:2,matchup_id:3},{roster_id:3,matchup_id:3}],'1').opponent,null,'No arbitrary opponent in multi-team pair');
assert.strictEqual(w.pairing([{roster_id:1,matchup_id:null},{roster_id:2,matchup_id:null}],'1').opponent,null);
assert.match(w.forecastAvailability(),/verified pregame cutoff/);
assert.strictEqual(w.scoring(null,c,0).exact,false,'Missing stats cannot become exact scoring');
console.log('PASS: editorial Weekly outcomes, null/zero/negative points, pairing, timezone and fail-closed forecast semantics');
