/* Runtime integrity for league snapshot prefetch + non-blocking live overlay. */
'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const code=fs.readFileSync('app/core/data-client.js','utf8');
const lid='123456789012345678';let directLeagueFetches=0,snapshotFetches=0,indexFetches=0;
const stores=new Map();
const fakeCaches={async open(name){if(!stores.has(name))stores.set(name,new Map());const store=stores.get(name);return{async match(req){const r=store.get(req.url);return r?r.clone():undefined;},async put(req,res){store.set(req.url,res.clone());},async delete(req){return store.delete(req.url);}};},async delete(name){return stores.delete(name);}};
const reply=o=>new Response(JSON.stringify(o),{status:200,headers:{'content-type':'application/json'}});
const fetch=async url=>{const s=String(url);if(s.endsWith('/data/research/app/league-index.json')){indexFetches++;return reply({schema:'fie-league-index-v1',leagues:[{league_id:lid,priority:'HIGH'}]});}if(s.includes(`/data/research/leagues/${lid}/app/core.json`)){snapshotFetches++;return reply({schema:'fie-league-core-v1',league_id:lid,sleeper:{league:{league_id:lid,name:'Snapshot'},rosters:[{roster_id:1,players:['old']}],users:[{user_id:'u1',display_name:'Snapshot User'}]}});}if(s===`https://api.sleeper.app/v1/league/${lid}`){directLeagueFetches++;return reply({league_id:lid,name:'Live'});}if(s===`https://api.sleeper.app/v1/league/${lid}/rosters`)return reply([{roster_id:1,players:['live']}]);if(s===`https://api.sleeper.app/v1/league/${lid}/users`)return reply([{user_id:'u1',display_name:'Live User'}]);throw new Error(`unexpected fetch ${s}`);};
class CE{constructor(type,init={}){this.type=type;this.detail=init.detail;}}
const ctx={console,window:null,caches:fakeCaches,Request,Response,Headers,URL,AbortController,DOMException,Date,Math,Map,Set,Promise,setTimeout,clearTimeout,performance:{now:()=>Date.now()},location:{href:'https://example.test/',origin:'https://example.test'},fetch,navigator:{connection:{effectiveType:'4g',saveData:false}},document:{readyState:'loading',visibilityState:'visible',addEventListener(){}},CustomEvent:CE};
ctx.window=ctx;ctx.addEventListener=()=>{};ctx.dispatchEvent=()=>true;ctx.FIECore={Diagnostics:{capture(e){throw e;}}};vm.createContext(ctx);vm.runInContext(code,ctx,{filename:'data-client.js'});
(async()=>{const c=ctx.FIEDataClient;await c.prefetchLeagueSnapshots();assert.strictEqual(indexFetches,1);assert.strictEqual(snapshotFetches,1);const league=await c.json(`https://api.sleeper.app/v1/league/${lid}`);assert.strictEqual(league.name,'Snapshot','snapshot must hydrate without waiting for live Sleeper');await new Promise(r=>setTimeout(r,20));assert.strictEqual(league.name,'Live','live overlay must mutate hydrated object in place');assert.strictEqual(directLeagueFetches,1);const rosters=await c.json(`https://api.sleeper.app/v1/league/${lid}/rosters`);assert.strictEqual(rosters[0].players[0],'old');await new Promise(r=>setTimeout(r,20));assert.strictEqual(rosters[0].players[0],'live');const st=c.cacheStats();assert.ok(st.leagueSnapshotHits>=1);assert.ok(st.liveRefreshes>=2);console.log('PASS league fast-switch runtime: prefetched snapshot hydrates first; live state patches asynchronously');})().catch(e=>{console.error(e);process.exit(1);});
