/* FIE managed portfolio configuration + custom cohort rules.
 * The managed league list is server-backed; localStorage remains a cache/UI layer.
 */
(function(){
'use strict';
const CONFIG_URL='config/league-portfolio.json';
const STATUS_URL='data/research/leagues/portfolio-status.json';
const SAVED_KEY='fieSavedLeaguesV71';
const FORMAT_LABELS={REDRAFT:'Redraft',DYNASTY:'Dynasty',CHOPPED:'Chopped',REDRAFT_BESTBALL:'Redraft + Best Ball',DYNASTY_BESTBALL:'Dynasty + Best Ball'};
const API={version:'1.0.0',config:null,status:null,loaded:false,error:null};
function readJSON(key,fallback){try{const x=JSON.parse(localStorage.getItem(key)||'null');return x&&typeof x==='object'?x:fallback;}catch{return fallback;}}
function writeJSON(key,x){try{localStorage.setItem(key,JSON.stringify(x));}catch{}}
function num(x){const n=Number(x);return Number.isFinite(n)?n:null;}
function activeSeason(){const s=num(window.state?.league?.season);if(s)return s;const d=new Date();return d.getUTCMonth()<=1?d.getUTCFullYear()-1:d.getUTCFullYear();}
function entryFor(id){const lid=String(id||'');return API.config?.leagues?.find(x=>String(x.league_id)===lid)||null;}
function statusFor(id){return API.status?.leagues?.[String(id)]||null;}
function constraintsFor(id){return entryFor(id)?.research_constraints||[];}
function playerEntrySeason(p){for(const k of ['entryClass','entrySeason','entryYear','draftYear','rookieYear']){const v=num(p?.[k]);if(v&&v>1990&&v<2100)return Math.round(v);}const y=num(p?.yearsExp);if(y!==null&&y>=0)return activeSeason()-Math.round(y);return null;}
function managedLeagues(){return (API.config?.leagues||[]).filter(x=>x.enabled!==false).map(e=>{const st=statusFor(e.league_id)||{};return{id:String(e.league_id),name:e.alias||st.league_name||'',season:st.season||'',formatOverride:e.format||'AUTO',managed:true,priority:e.priority||'MEDIUM',researchStatus:st.status||'NOT_BUILT',researchConstraints:e.research_constraints||[]};});}
function mergeManagedIntoLocal(){if(!API.loaded)return;const local=readJSON(SAVED_KEY,[]),by=new Map((Array.isArray(local)?local:[]).map(x=>[String(x.id),x]));for(const m of managedLeagues()){const old=by.get(String(m.id))||{};by.set(String(m.id),{...old,...m,name:(old.name&&old.name!==String(m.id))?old.name:m.name,formatOverride:m.formatOverride,managed:true});}const merged=[...by.values()];writeJSON(SAVED_KEY,merged);if(window.state)window.state.savedLeagues=merged;window.renderSavedLeagueControlsV71?.();}
function applyLeagueRules(state,id){const e=entryFor(id);if(!e||!state?.leagueRules)return state?.leagueRules;state.leagueRules.format=e.format||state.leagueRules.format;state.leagueRules.portfolioManaged=true;state.leagueRules.researchConstraints=e.research_constraints||[];state.leagueRules.portfolioPriority=e.priority||'MEDIUM';return state.leagueRules;}
function cohortFloorConstraint(id){return constraintsFor(id).find(x=>x.type==='nfl_entry_cohort_floor')||null;}
function legacyConstraint(id){return constraintsFor(id).find(x=>x.type==='cohort_floor_with_legacy_cap')||null;}
function isPlayerEligible(p,base,state){if(!base)return false;const lid=String(state?.league?.league_id||'');const floor=cohortFloorConstraint(lid);if(floor){const y=playerEntrySeason(p);return y!==null&&y>=Number(floor.minimum_entry_season);}return true;}
function legacyCapFor(c,season){const caps=c?.legacy_cap_by_season||{},s=String(Number(season)||activeSeason());if(caps[s]!==undefined)return Number(caps[s]);const years=Object.keys(caps).map(Number).filter(Number.isFinite).sort((a,b)=>a-b);if(years.length&&Number(s)>years[years.length-1])return Number(c.legacy_cap_after_2030??caps[String(years[years.length-1])]);return null;}
function isLegacy(p,c){const y=playerEntrySeason(p);return y===null||y<=Number(c.legacy_entry_season_max??Number(c.unlimited_entry_season_min)-1);}
function legacyCount(rosterId,c,players){return (players||[]).filter(p=>Number(p.ownerRosterId)===Number(rosterId)&&isLegacy(p,c)).length;}
function acquisitionConstraint(player,rosterId,base,state,players){if(base?.legal===false)return base;const lid=String(state?.league?.league_id||''),c=legacyConstraint(lid);if(!c||!isLegacy(player,c))return base;const cap=legacyCapFor(c,state?.league?.season||activeSeason());if(!Number.isFinite(cap))return base;const count=legacyCount(rosterId,c,players);if(count>=cap)return{legal:true,requiresDrop:true,reason:`Legacy veteran cap ${count}/${cap}: acquiring another pre-${c.unlimited_entry_season_min} player requires a legacy-veteran drop or trade.`};return base;}
function rosterRuleViolations(rosterId,base,state,players){const out=[...(base||[])],lid=String(state?.league?.league_id||''),c=legacyConstraint(lid),floor=cohortFloorConstraint(lid);if(c){const cap=legacyCapFor(c,state?.league?.season||activeSeason()),count=legacyCount(rosterId,c,players);if(Number.isFinite(cap)&&count>cap)out.push(`Legacy veterans: ${count}/${cap} (pre-${c.unlimited_entry_season_min} entry cohort)`);}if(floor){const bad=(players||[]).filter(p=>Number(p.ownerRosterId)===Number(rosterId)).filter(p=>{const y=playerEntrySeason(p);return y===null||y<Number(floor.minimum_entry_season);});if(bad.length)out.push(`${bad.length} rostered player(s) fall outside the fixed ${floor.minimum_entry_season}+ entry cohort`);}return out;}
function dropSatisfiesAcquisition(add,drop,state){const c=legacyConstraint(String(state?.league?.league_id||''));if(c&&isLegacy(add,c))return isLegacy(drop,c);return null;}
function poolViolations(pool,state){const out=[],lid=String(state?.league?.league_id||''),floor=cohortFloorConstraint(lid),c=legacyConstraint(lid);if(floor){const bad=(pool||[]).filter(p=>{const y=playerEntrySeason(p);return y===null||y<Number(floor.minimum_entry_season);});if(bad.length)out.push(`${bad.length} asset(s) outside the fixed ${floor.minimum_entry_season}+ entry cohort`);}if(c){const cap=legacyCapFor(c,state?.league?.season||activeSeason()),n=(pool||[]).filter(p=>isLegacy(p,c)).length;if(Number.isFinite(cap)&&n>cap)out.push(`legacy-veteran cap exceeded: ${n}/${cap}`);}const limits=state?.leagueRules?.maxByExperience||{};if(window.experienceBucket){for(const [k,capRaw] of Object.entries(limits)){const cap=Number(capRaw);if(!Number.isFinite(cap))continue;const n=(pool||[]).filter(p=>window.experienceBucket(p?.yearsExp)===k).length;if(n>cap)out.push(`${k} cap exceeded: ${n}/${cap}`);}}return out;}
function ruleSummary(id,season){const out=[];for(const c of constraintsFor(id)){if(c.type==='nfl_entry_cohort_floor')out.push(`Only NFL entry class ${c.minimum_entry_season} or newer is eligible; that cohort floor stays fixed as new rookie classes are added.`);if(c.type==='cohort_floor_with_legacy_cap'){const cap=legacyCapFor(c,season||activeSeason());out.push(`NFL entry class ${c.unlimited_entry_season_min}+ is permanently unrestricted. Pre-${c.unlimited_entry_season_min} legacy veterans are capped at ${cap??'—'} this season.`);}}return out;}
async function load(){try{const [cr,sr]=await Promise.all([fetch(CONFIG_URL,{cache:'no-store'}),fetch(STATUS_URL,{cache:'no-store'}).catch(()=>null)]);if(!cr.ok)throw new Error(`portfolio config HTTP ${cr.status}`);API.config=await cr.json();if(sr?.ok)API.status=await sr.json();API.loaded=true;mergeManagedIntoLocal();window.FIEPortfolio?.render?.();window.FIEPortfolio?.refreshStatuses?.(false);return API;}catch(e){API.error=String(e?.message||e);API.loaded=true;console.warn('Managed portfolio config unavailable',e);return API;}}
Object.assign(API,{entryFor,statusFor,constraintsFor,managedLeagues,mergeManagedIntoLocal,applyLeagueRules,isPlayerEligible,acquisitionConstraint,rosterRuleViolations,dropSatisfiesAcquisition,poolViolations,ruleSummary,playerEntrySeason,legacyCapFor,load});
window.FIEPortfolioConfig=API;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>load());else load();
})();
