/* FIE centralized fetch/request layer, V9.3.3 fast-switch foundation.
 * Memory cache + in-flight coalescing remain the hot path. Stable shared NFL
 * proxy payloads use Cache Storage. Compact league shell snapshots hydrate
 * Sleeper league/roster/user reads immediately, then a non-blocking live fetch
 * mutates the returned object in-place and emits fie:league-live-update.
 */
(function(){
'use strict';
const D=()=>window.FIECore?.Diagnostics;
const memory=new Map(),inflight=new Map(),leagueSnapshots=new Map(),leagueSnapshotInflight=new Map(),knownLeagueIds=new Set();
const stats={hits:0,misses:0,coalesced:0,stores:0,persistentHits:0,persistentMisses:0,persistentStores:0,persistentErrors:0,leagueSnapshotHits:0,leagueSnapshotMisses:0,leagueSnapshotStores:0,liveRefreshes:0,liveRefreshErrors:0,prefetchedLeagues:0};
const PERSISTENT_CACHE='fie-data-v932',LEAGUE_CACHE='fie-league-core-v1',LEAGUE_INDEX='/data/research/app/league-index.json';
function ttlFor(url){const u=String(url||'');if(/sleeper\/players/.test(u))return 6*3600e3;if(/nflverse\/(players|contracts)/.test(u))return 12*3600e3;if(/nflverse\/(stats|snaps|weekly|schedule|depth|team)/.test(u))return 6*3600e3;if(/projection/i.test(u))return 5*60e3;if(/research|milestone|current/i.test(u))return 10*60e3;return 60e3;}
function cacheable(opts){return String(opts?.method||'GET').toUpperCase()==='GET'&&opts?.cache!=='no-store'&&opts?.dedupe!==false;}
function keyFor(kind,url){return `${kind}:${String(url)}`;}
function absolute(url){try{return new URL(String(url),window.location?.href||'https://fie.local/').href;}catch{return String(url||'');}}
function persistable(url,opts={}){if(opts.persist===false||opts.cache==='no-store'||String(opts.method||'GET').toUpperCase()!=='GET')return false;if(opts.persist===true)return true;const u=absolute(url);return /\/api\/data\/(?:nflverse\/|sleeper\/players(?:$|[/?])|sleeper\/projections\/)/i.test(u);}
function fnv(str){let h=2166136261>>>0;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0).toString(16).padStart(8,'0');}
function persistentRequest(kind,url){const origin=window.location?.origin||'https://fie.local',abs=absolute(url);return new Request(`${origin}/__fie_cache__/v932/${kind}/${fnv(abs)}`,{method:'GET'});}
async function persistentGet(kind,url,ttl){if(!('caches'in window)||typeof Response==='undefined'||typeof Request==='undefined')return null;const abs=absolute(url);try{const c=await caches.open(PERSISTENT_CACHE),req=persistentRequest(kind,url),hit=await c.match(req);if(!hit){stats.persistentMisses++;return null;}const stored=Number(hit.headers.get('x-fie-cache-at')||0),source=hit.headers.get('x-fie-cache-url')||'';if(source!==abs||!stored||Date.now()-stored>=ttl){stats.persistentMisses++;await c.delete(req).catch(()=>{});return null;}const value=kind==='json'?await hit.json():await hit.text();stats.persistentHits++;return{at:stored,value};}catch(e){stats.persistentErrors++;D()?.capture?.(e,{domain:'persistent-cache-read',url:abs});return null;}}
async function persistentSet(kind,url,value){if(!('caches'in window)||typeof Response==='undefined'||typeof Request==='undefined')return;const abs=absolute(url);try{const body=kind==='json'?JSON.stringify(value):String(value??''),headers={'content-type':kind==='json'?'application/json; charset=utf-8':'text/plain; charset=utf-8','x-fie-cache-at':String(Date.now()),'x-fie-cache-url':abs,'x-fie-cache-kind':kind};const c=await caches.open(PERSISTENT_CACHE);await c.put(persistentRequest(kind,url),new Response(body,{status:200,headers}));stats.persistentStores++;}catch(e){stats.persistentErrors++;D()?.capture?.(e,{domain:'persistent-cache-write',url:abs});}}
function redacted(url){return D()?.redact?.(url)||String(url||'');}
function mergeSignals(a,b){if(!a)return b;if(!b)return a;const c=new AbortController(),stop=()=>c.abort();if(a.aborted||b.aborted)c.abort();else{a.addEventListener('abort',stop,{once:true});b.addEventListener('abort',stop,{once:true});}return c.signal;}
function clone(value){try{return typeof structuredClone==='function'?structuredClone(value):JSON.parse(JSON.stringify(value));}catch{return value;}}
function mutate(target,value){if(Array.isArray(target)&&Array.isArray(value)){target.splice(0,target.length,...value);return target;}if(target&&value&&typeof target==='object'&&typeof value==='object'&&!Array.isArray(target)&&!Array.isArray(value)){for(const k of Object.keys(target))if(!(k in value))delete target[k];Object.assign(target,value);return target;}return value;}
function sleeperLeagueRoute(url){let u;try{u=new URL(String(url),window.location?.href||'https://fie.local/');}catch{return null;}if(!/(?:^|\.)sleeper\.(?:app|com)$/i.test(u.hostname))return null;const m=u.pathname.match(/^\/v1\/league\/(\d{6,32})(?:\/(rosters|users))?\/?$/);if(!m)return null;return{leagueId:m[1],part:m[2]||'league'};}
function snapshotUrl(leagueId){return `/data/research/leagues/${encodeURIComponent(leagueId)}/app/core.json`;}
function leagueCacheRequest(leagueId){const origin=window.location?.origin||'https://fie.local';return new Request(`${origin}/__fie_cache__/league-core/${leagueId}`,{method:'GET'});}
async function leagueSnapshotDiskGet(leagueId){if(!('caches'in window))return null;try{const c=await caches.open(LEAGUE_CACHE),r=await c.match(leagueCacheRequest(leagueId));if(!r)return null;const value=await r.json(),at=Number(r.headers.get('x-fie-cache-at')||0);if(!value||value.schema!=='fie-league-core-v1')return null;return{at,value};}catch(e){D()?.capture?.(e,{domain:'league-snapshot-cache-read',leagueId});return null;}}
async function leagueSnapshotDiskSet(leagueId,value){if(!('caches'in window))return;try{const c=await caches.open(LEAGUE_CACHE);await c.put(leagueCacheRequest(leagueId),new Response(JSON.stringify(value),{headers:{'content-type':'application/json','x-fie-cache-at':String(Date.now())}}));stats.leagueSnapshotStores++;}catch(e){D()?.capture?.(e,{domain:'league-snapshot-cache-write',leagueId});}}
async function loadLeagueSnapshot(leagueId,{force=false}={}){const id=String(leagueId);if(!force&&leagueSnapshots.has(id)){stats.leagueSnapshotHits++;return leagueSnapshots.get(id);}if(!force&&leagueSnapshotInflight.has(id))return leagueSnapshotInflight.get(id);const p=(async()=>{if(!force){const disk=await leagueSnapshotDiskGet(id);if(disk){leagueSnapshots.set(id,disk.value);stats.leagueSnapshotHits++;return disk.value;}}stats.leagueSnapshotMisses++;const started=performance.now();const r=await fetch(snapshotUrl(id),{cache:force?'reload':'default'});if(!r.ok)throw new Error(`HTTP ${r.status} loading league snapshot ${id}`);const value=await r.json();if(value?.schema!=='fie-league-core-v1'||String(value?.league_id||'')!==id)throw new Error(`Invalid league snapshot ${id}`);leagueSnapshots.set(id,value);await leagueSnapshotDiskSet(id,value);window.FIEPerformance?.push?.('league-snapshot',performance.now()-started,{leagueId:id,bytes:Number(r.headers.get('content-length')||0)});return value;})().finally(()=>leagueSnapshotInflight.delete(id));leagueSnapshotInflight.set(id,p);return p;}
function snapshotPart(core,part){const value=core?.sleeper?.[part];if(part==='league'&&value&&typeof value==='object')return clone(value);if((part==='rosters'||part==='users')&&Array.isArray(value))return clone(value);return null;}
async function nativeLiveJSON(url,opts={}){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(new DOMException('Timeout','AbortError')),Number(opts.timeoutMs)||8000),signal=mergeSignals(opts.signal,ctl.signal);try{const r=await fetch(url,{signal,cache:'no-store',headers:opts.headers||{}});if(!r.ok)throw new Error(`HTTP ${r.status} ${r.statusText}`);return r.json();}finally{clearTimeout(timer);}}
function liveRefresh(route,url,target,opts={}){if(opts.liveOverlay===false)return;Promise.resolve().then(async()=>{try{const value=await nativeLiveJSON(url,{signal:opts.signal,timeoutMs:opts.liveTimeoutMs||8000,headers:opts.headers});mutate(target,value);memory.set(keyFor('json',url),{at:Date.now(),value:target});stats.liveRefreshes++;window.dispatchEvent?.(new CustomEvent('fie:league-live-update',{detail:{leagueId:route.leagueId,part:route.part,value:target,at:Date.now()}}));}catch(e){stats.liveRefreshErrors++;if(e?.name!=='AbortError')D()?.capture?.(e,{domain:'league-live-overlay',leagueId:route.leagueId,part:route.part,url:redacted(url)});}});}
async function tryLeagueSnapshot(url,opts={}){if(opts.live===true||opts.snapshot===false||opts.cache==='no-store')return null;const route=sleeperLeagueRoute(url);if(!route||!knownLeagueIds.has(route.leagueId))return null;try{const core=await loadLeagueSnapshot(route.leagueId),value=snapshotPart(core,route.part);if(value==null)return null;liveRefresh(route,url,value,opts);return{route,value};}catch(e){D()?.capture?.(e,{domain:'league-snapshot-fallback',leagueId:route.leagueId,url:redacted(url)});return null;}}
async function refreshLeague(leagueId,{timeoutMs=8000}={}){const id=String(leagueId),base=`https://api.sleeper.app/v1/league/${id}`,parts=['league','rosters','users'],out={};await Promise.all(parts.map(async part=>{const url=part==='league'?base:`${base}/${part}`,value=await nativeLiveJSON(url,{timeoutMs});out[part]=value;memory.set(keyFor('json',url),{at:Date.now(),value});window.dispatchEvent?.(new CustomEvent('fie:league-live-update',{detail:{leagueId:id,part,value,at:Date.now(),manual:true}}));}));return out;}
function connectionPolicy(){const n=typeof navigator!=='undefined'?navigator:{};const c=n.connection||n.mozConnection||n.webkitConnection;if(c?.saveData)return'none';const e=String(c?.effectiveType||'').toLowerCase();if(e==='slow-2g'||e==='2g')return'priority';return'all';}
async function prefetchLeagueSnapshots(){if(document.visibilityState==='hidden')return;const policy=connectionPolicy();if(policy==='none')return;let index;try{const r=await fetch(LEAGUE_INDEX,{cache:'default'});if(!r.ok)return;index=await r.json();}catch{return;}let rows=Array.isArray(index?.leagues)?index.leagues:[];for(const row of rows){const id=String(row?.league_id||'');if(id)knownLeagueIds.add(id);}if(policy==='priority')rows=rows.filter(x=>x?.priority==='VERY_HIGH'||x?.priority==='HIGH').slice(0,6);const queue=rows.map(x=>String(x.league_id||'')).filter(Boolean),workers=[];for(let i=0;i<2;i++)workers.push((async()=>{while(queue.length){if(document.visibilityState==='hidden')return;const id=queue.shift();try{await loadLeagueSnapshot(id);stats.prefetchedLeagues++;}catch{}await new Promise(r=>setTimeout(r,50));}})());await Promise.all(workers);}
function schedulePrefetch(){if(typeof document==='undefined')return;const run=()=>{const idle=window.requestIdleCallback||((fn)=>setTimeout(fn,250));idle(()=>prefetchLeagueSnapshots(),{timeout:4000});};if(document.readyState==='complete')setTimeout(run,1500);else window.addEventListener('load',()=>setTimeout(run,1500),{once:true});}
const Client={
  version:'9.3.3-data-client-fast-switch',defaultTimeoutMs:12000,scopeSignal:null,
  setScope(signal){this.scopeSignal=signal||null;},
  async request(url,{signal=this.scopeSignal,timeoutMs=this.defaultTimeoutMs,cache='default',method='GET',headers={},expect='auto',sourceId=null,maxBytes=20*1024*1024}={}){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(new DOMException('Timeout','AbortError')),timeoutMs),combined=mergeSignals(signal,ctl.signal),started=performance.now();try{const r=await fetch(url,{signal:combined,cache,method,headers});const len=Number(r.headers.get('content-length')||0);if(len&&len>maxBytes)throw new Error(`Response too large (${len} bytes)`);if(!r.ok)throw new Error(`HTTP ${r.status} ${r.statusText}`);window.FIEPerformance?.push?.(`fetch:${sourceId||new URL(String(url),location.href).pathname}`,performance.now()-started,{status:r.status});if(expect==='response')return r;const ct=String(r.headers.get('content-type')||'').toLowerCase();if(expect==='json'||(expect==='auto'&&ct.includes('json')))return r.json();if(expect==='text'||expect==='auto')return r.text();return r;}catch(e){if(e?.name!=='AbortError')D()?.capture?.(e,{domain:'fetch',sourceId,url:redacted(url)});throw e;}finally{clearTimeout(timer);}},
  async _cached(kind,url,opts={}){if(kind==='json'&&cacheable(opts)){const snap=await tryLeagueSnapshot(url,opts);if(snap){stats.hits++;memory.set(keyFor(kind,url),{at:Date.now(),value:snap.value});return snap.value;}}if(!cacheable(opts))return this.request(url,{...opts,expect:kind});const key=keyFor(kind,url),now=Date.now(),hit=memory.get(key),ttl=Number.isFinite(Number(opts.ttlMs))?Number(opts.ttlMs):ttlFor(url);if(hit&&now-hit.at<ttl){stats.hits++;return hit.value;}if(inflight.has(key)){stats.coalesced++;return inflight.get(key);}stats.misses++;const promise=(async()=>{if(persistable(url,opts)){const disk=await persistentGet(kind,url,ttl);if(disk){memory.set(key,disk);return disk.value;}}const value=await this.request(url,{...opts,expect:kind});const row={at:Date.now(),value};memory.set(key,row);stats.stores++;if(persistable(url,opts))await persistentSet(kind,url,value);return value;})().finally(()=>inflight.delete(key));inflight.set(key,promise);return promise;},
  json(url,opts={}){return this._cached('json',url,opts);},
  text(url,opts={}){return this._cached('text',url,opts);},
  response(url,opts={}){return this.request(url,{...opts,expect:'response'});},
  loadLeagueSnapshot,
  refreshLeague,
  prefetchLeagueSnapshots,
  sanitizeUrl:redacted,
  cacheStats(){return {...stats,inflightHits:stats.coalesced,entries:memory.size,memoryEntries:memory.size,inflight:inflight.size,leagueSnapshots:leagueSnapshots.size,persistentCache:PERSISTENT_CACHE,leagueCache:LEAGUE_CACHE};},
  clearMemory(){memory.clear();inflight.clear();leagueSnapshots.clear();leagueSnapshotInflight.clear();},
  async clearPersistent(){let ok=true;if('caches'in window){try{ok=(await caches.delete(PERSISTENT_CACHE))&&ok;}catch{ok=false;}try{await caches.delete(LEAGUE_CACHE);}catch{ok=false;}return ok;}return false;}
};
window.FIEDataClient=Client;schedulePrefetch();
})();
